/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista.menuPrincipal;

import Control.ClienteData;
import Modelo.Cliente;
import java.util.concurrent.ExecutionException;
import javax.swing.JOptionPane;

/**
 *
 * @author Hugo
 */
public class agregarCliente extends javax.swing.JFrame {
   
    ClienteData cliData =new ClienteData();

    /**
     * Creates new form agregarCliente
     */
    public agregarCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jT_nombreCliente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jT_apellidoCliente = new javax.swing.JTextField();
        jT_direccionCliente = new javax.swing.JTextField();
        jT_idCliente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jT_telefonoCliente = new javax.swing.JTextField();
        jB_EliminarCliente = new javax.swing.JButton();
        jB_EditarCliente = new javax.swing.JButton();
        jB_AgregarCliente = new javax.swing.JButton();
        jB_buscarCliente = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jB_Limpiar = new javax.swing.JButton();

        jLabel3.setText("Nombre");
        jLabel3.setMinimumSize(new java.awt.Dimension(50, 16));
        jLabel3.setPreferredSize(new java.awt.Dimension(50, 15));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 500));
        setPreferredSize(new java.awt.Dimension(800, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMinimumSize(new java.awt.Dimension(800, 500));

        jLabel1.setText("Formulario Cliente");

        jLabel2.setText("ID Cliente");
        jLabel2.setPreferredSize(new java.awt.Dimension(50, 15));

        jLabel4.setText("Apellido");

        jLabel5.setText("Direccion");

        jLabel6.setText("Telefono");

        jB_EliminarCliente.setText("Eliminar ");
        jB_EliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_EliminarClienteActionPerformed(evt);
            }
        });

        jB_EditarCliente.setText("Editar");
        jB_EditarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_EditarClienteActionPerformed(evt);
            }
        });

        jB_AgregarCliente.setText("Agregar ");
        jB_AgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_AgregarClienteActionPerformed(evt);
            }
        });

        jB_buscarCliente.setText("Buscar");
        jB_buscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_buscarClienteActionPerformed(evt);
            }
        });

        jLabel7.setText("Nombre");

        jB_Limpiar.setText("Limpiar");
        jB_Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_LimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jT_idCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                            .addComponent(jT_nombreCliente)
                            .addComponent(jT_apellidoCliente)
                            .addComponent(jT_direccionCliente)
                            .addComponent(jT_telefonoCliente))
                        .addGap(101, 101, 101)
                        .addComponent(jB_buscarCliente))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(jB_AgregarCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jB_EditarCliente)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jB_Limpiar)
                            .addComponent(jB_EliminarCliente))))
                .addContainerGap(260, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jT_idCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_buscarCliente))
                .addGap(1, 1, 1)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jT_nombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4))
                    .addComponent(jT_apellidoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jT_direccionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jT_telefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jB_Limpiar)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_AgregarCliente)
                    .addComponent(jB_EditarCliente)
                    .addComponent(jB_EliminarCliente))
                .addContainerGap(135, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jB_AgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_AgregarClienteActionPerformed
        // TODO add your handling code here:
        try {
            String nom = jT_nombreCliente.getText();
            String ape = jT_apellidoCliente.getText();
            String dir = jT_direccionCliente.getText();
            String telString = jT_telefonoCliente.getText();
            long tel = 0;

            try {
                tel = Long.parseLong(telString);
            } catch (NumberFormatException e) {
                // Manejar el caso en el que el número de teléfono no sea un entero válido
                JOptionPane.showMessageDialog(this, "Número de teléfono no válido.");
                return;
            }

            Cliente cli = new Cliente(ape, nom, dir, telString);
            cliData.agregarCliente(cli);
            Limpiar();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al Guardar." + ex.getMessage());
        }
    }//GEN-LAST:event_jB_AgregarClienteActionPerformed

    private void jB_EditarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_EditarClienteActionPerformed
        // TODO add your handling code here:
        
        try{
            int id = Integer.parseInt(jT_idCliente.getText());
            String nom = jT_nombreCliente.getText();
            String ape = jT_apellidoCliente.getText();
            String dom = jT_direccionCliente.getText();
            String tel = jT_telefonoCliente.getText();
            Cliente cli = new Cliente(id, ape, nom, dom, tel);
            cliData.modificarCliente(cli);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Error al Actualizar"+ex.getMessage());
        }
        
    }//GEN-LAST:event_jB_EditarClienteActionPerformed

    private void jB_buscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_buscarClienteActionPerformed
        // TODO add your handling code here:
        
        try{
            int id = Integer.parseInt(jT_idCliente.getText());
            Cliente clienteEncontrado = cliData.buscarClientePorId(id);
            if(clienteEncontrado != null ){
                String nom = clienteEncontrado.getNombre();
                String ape = clienteEncontrado.getApellido();
                String dom = clienteEncontrado.getDomicilio();
                String tel = clienteEncontrado.getTelefono();
                jT_nombreCliente.setText(nom);
                jT_apellidoCliente.setText(ape);
                jT_direccionCliente.setText(dom);
                jT_telefonoCliente.setText(tel);
            }else{
                JOptionPane.showMessageDialog(this, "Cliente no encontrado.");
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Error al buscar."+ex.getMessage());
        }
    }//GEN-LAST:event_jB_buscarClienteActionPerformed

    private void jB_EliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_EliminarClienteActionPerformed
        // TODO add your handling code here:
        try{
            int id = Integer.parseInt(jT_idCliente.getText());
            cliData.eliminarCliente(id);
            JOptionPane.showMessageDialog(this, "Cliente eliminado.");
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Error al eliminar al cliente."+ex.getMessage());
        }
        
        
    }//GEN-LAST:event_jB_EliminarClienteActionPerformed

    private void jB_LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_LimpiarActionPerformed
        // TODO add your handling code here:
        jT_idCliente.setText("");
        jT_nombreCliente.setText("");
        jT_apellidoCliente.setText("");
        jT_direccionCliente.setText("");
        jT_telefonoCliente.setText("");
    }//GEN-LAST:event_jB_LimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(agregarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(agregarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(agregarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(agregarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new agregarCliente().setVisible(true);
            }
        });
    }
    public void Limpiar(){
        jT_idCliente.setText("");
        jT_nombreCliente.setText("");
        jT_apellidoCliente.setText("");
        jT_direccionCliente.setText("");
        jT_telefonoCliente.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_AgregarCliente;
    private javax.swing.JButton jB_EditarCliente;
    private javax.swing.JButton jB_EliminarCliente;
    private javax.swing.JButton jB_Limpiar;
    private javax.swing.JButton jB_buscarCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jT_apellidoCliente;
    private javax.swing.JTextField jT_direccionCliente;
    private javax.swing.JTextField jT_idCliente;
    private javax.swing.JTextField jT_nombreCliente;
    private javax.swing.JTextField jT_telefonoCliente;
    // End of variables declaration//GEN-END:variables
}
