/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista.menuPrincipal;

import Control.ClienteData;
import Control.DetalleVentaData;
import Control.ProductoData;
import Control.VentaData;
import Modelo.Cliente;
import Modelo.DetalleVenta;
import Modelo.Producto;
import Modelo.Venta;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hugo, APOLO
 */
public class vistaVenta extends javax.swing.JFrame {

    int xMouse, yMouse;
    private DefaultTableModel modelo = new DefaultTableModel();
    private DefaultTableModel modeloproducto = new DefaultTableModel();
    private DefaultTableModel modeloidVenta = new DefaultTableModel();
    private VentaData ventaData = new VentaData();
    private ClienteData cliData = new ClienteData();
    private ProductoData proData = new ProductoData();
    private int idVenta;

    //Componentes
    public vistaVenta() {
        initComponents();
        armarCabeceracliente();
        llenarCabeceraCliente();
        armarCabeceraProductos();
        llenarCabeceraProductos();
        armarCabeceraIdVenta();
        llenarTablaIdVenta();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jP_header = new javax.swing.JPanel();
        HomeBtn = new javax.swing.JPanel();
        HomeBtnTxt = new javax.swing.JLabel();
        BtnExit = new javax.swing.JPanel();
        BtnExitTxt = new javax.swing.JLabel();
        JL_LOGO = new javax.swing.JLabel();
        jL_Titulo = new javax.swing.JLabel();
        jS_LineaSeparadora = new javax.swing.JSeparator();
        jL_idCliente = new javax.swing.JLabel();
        jT_idCliente = new javax.swing.JTextField();
        jB_buscarClienteID = new javax.swing.JButton();
        jT_mostrarNombreCliente = new javax.swing.JTextField();
        jL_FechaCompra = new javax.swing.JLabel();
        jC_fechaCompra = new com.toedter.calendar.JDateChooser();
        jL_tituloTablaClientes = new javax.swing.JLabel();
        jS_mostrarClientes = new javax.swing.JScrollPane();
        jT_mostrarClientes = new javax.swing.JTable();
        jS_LineaSeparadora2 = new javax.swing.JSeparator();
        jL_TituloDetalleDeVenta = new javax.swing.JLabel();
        jL_ProductoId = new javax.swing.JLabel();
        jT_IDProducto = new javax.swing.JTextField();
        jB_Ok = new javax.swing.JButton();
        jL_nombreDelProducto = new javax.swing.JLabel();
        jT_MostrarNombreProducto = new javax.swing.JTextField();
        jL_Cantidad = new javax.swing.JLabel();
        jT_CantidadDeVenta = new javax.swing.JTextField();
        jL_PrecioVenta = new javax.swing.JLabel();
        jT_MostrarPrecioProducto = new javax.swing.JTextField();
        jL_tituloTablaProductos = new javax.swing.JLabel();
        jS_tablaProductos = new javax.swing.JScrollPane();
        jT_mostrarProductos = new javax.swing.JTable();
        jL_ultimoIdVenta = new javax.swing.JLabel();
        jS_ultimoIdVenta = new javax.swing.JScrollPane();
        jT_IdVenta = new javax.swing.JTable();
        jL_ultimoProductoID = new javax.swing.JLabel();
        jT_MostrarIdProducto_vender = new javax.swing.JTextField();
        jB_Vender = new javax.swing.JButton();
        jB_AgregarDetallesVenta = new javax.swing.JButton();
        jB_HistorialDeVentas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 800));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setMaximumSize(new java.awt.Dimension(800, 800));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 800));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 800));

        jP_header.setBackground(new java.awt.Color(51, 51, 51));
        jP_header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jP_headerMouseDragged(evt);
            }
        });
        jP_header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jP_headerMousePressed(evt);
            }
        });

        HomeBtn.setBackground(new java.awt.Color(51, 51, 51));

        HomeBtnTxt.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        HomeBtnTxt.setForeground(new java.awt.Color(255, 255, 255));
        HomeBtnTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HomeBtnTxt.setText("<");
        HomeBtnTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HomeBtnTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeBtnTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HomeBtnTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HomeBtnTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout HomeBtnLayout = new javax.swing.GroupLayout(HomeBtn);
        HomeBtn.setLayout(HomeBtnLayout);
        HomeBtnLayout.setHorizontalGroup(
            HomeBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 92, Short.MAX_VALUE)
            .addGroup(HomeBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(HomeBtnLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(HomeBtnTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        HomeBtnLayout.setVerticalGroup(
            HomeBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(HomeBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(HomeBtnLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(HomeBtnTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        BtnExit.setBackground(new java.awt.Color(51, 51, 51));
        BtnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        BtnExitTxt.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        BtnExitTxt.setForeground(new java.awt.Color(255, 255, 255));
        BtnExitTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtnExitTxt.setText("X");
        BtnExitTxt.setMaximumSize(new java.awt.Dimension(70, 70));
        BtnExitTxt.setMinimumSize(new java.awt.Dimension(70, 70));
        BtnExitTxt.setPreferredSize(new java.awt.Dimension(70, 70));
        BtnExitTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnExitTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnExitTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnExitTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout BtnExitLayout = new javax.swing.GroupLayout(BtnExit);
        BtnExit.setLayout(BtnExitLayout);
        BtnExitLayout.setHorizontalGroup(
            BtnExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BtnExitLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnExitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        BtnExitLayout.setVerticalGroup(
            BtnExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnExitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtnExitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JL_LOGO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagenes/LOGOCHIQUITO.png"))); // NOI18N
        JL_LOGO.setText("jLabel2");

        javax.swing.GroupLayout jP_headerLayout = new javax.swing.GroupLayout(jP_header);
        jP_header.setLayout(jP_headerLayout);
        jP_headerLayout.setHorizontalGroup(
            jP_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_headerLayout.createSequentialGroup()
                .addComponent(HomeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JL_LOGO, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(212, 212, 212)
                .addComponent(BtnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jP_headerLayout.setVerticalGroup(
            jP_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BtnExit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jP_headerLayout.createSequentialGroup()
                .addGroup(jP_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(HomeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JL_LOGO, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jL_Titulo.setFont(new java.awt.Font("HP Simplified", 1, 24)); // NOI18N
        jL_Titulo.setForeground(new java.awt.Color(204, 0, 204));
        jL_Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_Titulo.setText("VENTAS");

        jL_idCliente.setFont(new java.awt.Font("HP Simplified", 1, 15)); // NOI18N
        jL_idCliente.setForeground(new java.awt.Color(255, 255, 255));
        jL_idCliente.setText("CLIENTE ID");

        jT_idCliente.setFont(new java.awt.Font("HP Simplified", 1, 15)); // NOI18N
        jT_idCliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jB_buscarClienteID.setFont(new java.awt.Font("HP Simplified", 1, 15)); // NOI18N
        jB_buscarClienteID.setText("BUSCAR");
        jB_buscarClienteID.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jB_buscarClienteID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_buscarClienteIDActionPerformed(evt);
            }
        });

        jT_mostrarNombreCliente.setEditable(false);
        jT_mostrarNombreCliente.setFont(new java.awt.Font("HP Simplified", 1, 15)); // NOI18N
        jT_mostrarNombreCliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jL_FechaCompra.setFont(new java.awt.Font("HP Simplified", 1, 15)); // NOI18N
        jL_FechaCompra.setForeground(new java.awt.Color(255, 255, 255));
        jL_FechaCompra.setText("FECHA DE COMPRA");

        jC_fechaCompra.setForeground(new java.awt.Color(204, 0, 204));
        jC_fechaCompra.setToolTipText("");
        jC_fechaCompra.setFont(new java.awt.Font("HP Simplified", 0, 15)); // NOI18N

        jL_tituloTablaClientes.setFont(new java.awt.Font("HP Simplified", 1, 15)); // NOI18N
        jL_tituloTablaClientes.setForeground(new java.awt.Color(255, 255, 255));
        jL_tituloTablaClientes.setText("CLIENTES");

        jT_mostrarClientes.setFont(new java.awt.Font("HP Simplified", 0, 15)); // NOI18N
        jT_mostrarClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jT_mostrarClientes.setSelectionBackground(new java.awt.Color(204, 0, 204));
        jS_mostrarClientes.setViewportView(jT_mostrarClientes);

        jL_TituloDetalleDeVenta.setFont(new java.awt.Font("HP Simplified", 1, 24)); // NOI18N
        jL_TituloDetalleDeVenta.setForeground(new java.awt.Color(255, 255, 255));
        jL_TituloDetalleDeVenta.setText("DETALLE DE VENTA");

        jL_ProductoId.setFont(new java.awt.Font("HP Simplified", 1, 15)); // NOI18N
        jL_ProductoId.setForeground(new java.awt.Color(255, 255, 255));
        jL_ProductoId.setText("PRODUCTO ID");

        jT_IDProducto.setFont(new java.awt.Font("HP Simplified", 1, 15)); // NOI18N
        jT_IDProducto.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jB_Ok.setFont(new java.awt.Font("HP Simplified", 1, 15)); // NOI18N
        jB_Ok.setText("OK");
        jB_Ok.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jB_Ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_OkActionPerformed(evt);
            }
        });

        jL_nombreDelProducto.setFont(new java.awt.Font("HP Simplified", 1, 15)); // NOI18N
        jL_nombreDelProducto.setForeground(new java.awt.Color(255, 255, 255));
        jL_nombreDelProducto.setText("NOMBRE DEL PRODUCTO");

        jT_MostrarNombreProducto.setEditable(false);
        jT_MostrarNombreProducto.setFont(new java.awt.Font("HP Simplified", 1, 15)); // NOI18N

        jL_Cantidad.setFont(new java.awt.Font("HP Simplified", 1, 15)); // NOI18N
        jL_Cantidad.setForeground(new java.awt.Color(255, 255, 255));
        jL_Cantidad.setText("CANTIDAD");

        jT_CantidadDeVenta.setFont(new java.awt.Font("HP Simplified", 1, 15)); // NOI18N
        jT_CantidadDeVenta.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jL_PrecioVenta.setFont(new java.awt.Font("HP Simplified", 1, 15)); // NOI18N
        jL_PrecioVenta.setForeground(new java.awt.Color(255, 255, 255));
        jL_PrecioVenta.setText("PRECIO DE VENTA");

        jT_MostrarPrecioProducto.setEditable(false);
        jT_MostrarPrecioProducto.setFont(new java.awt.Font("HP Simplified", 1, 15)); // NOI18N
        jT_MostrarPrecioProducto.setForeground(new java.awt.Color(204, 51, 255));
        jT_MostrarPrecioProducto.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jL_tituloTablaProductos.setFont(new java.awt.Font("HP Simplified", 1, 15)); // NOI18N
        jL_tituloTablaProductos.setForeground(new java.awt.Color(255, 255, 255));
        jL_tituloTablaProductos.setText("PRODUCTOS");

        jT_mostrarProductos.setFont(new java.awt.Font("HP Simplified", 0, 15)); // NOI18N
        jT_mostrarProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jT_mostrarProductos.setSelectionBackground(new java.awt.Color(204, 0, 204));
        jS_tablaProductos.setViewportView(jT_mostrarProductos);

        jL_ultimoIdVenta.setFont(new java.awt.Font("HP Simplified", 1, 15)); // NOI18N
        jL_ultimoIdVenta.setForeground(new java.awt.Color(255, 255, 255));
        jL_ultimoIdVenta.setText("ULTIMO ID VENTA");

        jT_IdVenta.setFont(new java.awt.Font("HP Simplified", 0, 15)); // NOI18N
        jT_IdVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jT_IdVenta.setSelectionBackground(new java.awt.Color(204, 0, 204));
        jS_ultimoIdVenta.setViewportView(jT_IdVenta);

        jL_ultimoProductoID.setFont(new java.awt.Font("HP Simplified", 1, 15)); // NOI18N
        jL_ultimoProductoID.setForeground(new java.awt.Color(255, 255, 255));
        jL_ultimoProductoID.setText("ULTIMO PRODUCTO ID");

        jT_MostrarIdProducto_vender.setEditable(false);
        jT_MostrarIdProducto_vender.setFont(new java.awt.Font("HP Simplified", 0, 15)); // NOI18N

        jB_Vender.setFont(new java.awt.Font("HP Simplified", 1, 15)); // NOI18N
        jB_Vender.setText("VENDER");
        jB_Vender.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jB_Vender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_VenderActionPerformed(evt);
            }
        });

        jB_AgregarDetallesVenta.setFont(new java.awt.Font("HP Simplified", 1, 15)); // NOI18N
        jB_AgregarDetallesVenta.setText("GUARDAR DETALLES DE VENTA");
        jB_AgregarDetallesVenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jB_AgregarDetallesVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_AgregarDetallesVentaActionPerformed(evt);
            }
        });

        jB_HistorialDeVentas.setBackground(new java.awt.Color(255, 0, 255));
        jB_HistorialDeVentas.setFont(new java.awt.Font("HP Simplified", 1, 15)); // NOI18N
        jB_HistorialDeVentas.setForeground(new java.awt.Color(255, 255, 255));
        jB_HistorialDeVentas.setText("HISTORIAL DE VENTAS");
        jB_HistorialDeVentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jB_HistorialDeVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_HistorialDeVentasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jP_header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jS_LineaSeparadora2)
            .addComponent(jL_Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jS_LineaSeparadora, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jL_tituloTablaClientes)
                .addGap(173, 173, 173))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jL_TituloDetalleDeVenta)
                            .addComponent(jC_fechaCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jL_ProductoId)
                                        .addGap(18, 18, 18)
                                        .addComponent(jT_IDProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jT_MostrarNombreProducto, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jL_nombreDelProducto, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(jL_Cantidad)
                                    .addComponent(jT_CantidadDeVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jL_PrecioVenta))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jB_Ok))
                            .addComponent(jT_mostrarNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jL_FechaCompra)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jL_idCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jT_idCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jB_buscarClienteID))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jT_MostrarPrecioProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jB_Vender)))
                        .addGap(18, 18, 18)
                        .addComponent(jB_AgregarDetallesVenta)))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jL_ultimoProductoID)
                            .addComponent(jL_ultimoIdVenta))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jS_ultimoIdVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jT_MostrarIdProducto_vender, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jL_tituloTablaProductos)
                        .addGap(172, 172, 172))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jS_mostrarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jS_tablaProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jB_HistorialDeVentas)
                                .addGap(10, 10, 10)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jP_header, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jL_Titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jS_LineaSeparadora, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jL_tituloTablaClientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jT_idCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jB_buscarClienteID)
                            .addComponent(jL_idCliente))
                        .addGap(18, 18, 18)
                        .addComponent(jT_mostrarNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jL_FechaCompra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jC_fechaCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jS_mostrarClientes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jS_LineaSeparadora2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jL_tituloTablaProductos, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jL_TituloDetalleDeVenta))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jL_ProductoId)
                            .addComponent(jT_IDProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jB_Ok))
                        .addGap(11, 11, 11)
                        .addComponent(jL_nombreDelProducto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jT_MostrarNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jL_Cantidad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jT_CantidadDeVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jL_PrecioVenta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jT_MostrarPrecioProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jS_tablaProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jS_ultimoIdVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jL_ultimoIdVenta)
                                .addGap(18, 18, 18)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_ultimoProductoID)
                    .addComponent(jT_MostrarIdProducto_vender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_HistorialDeVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_Vender)
                    .addComponent(jB_AgregarDetallesVenta))
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mostrarAlerta(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje);
    }

    private void jB_buscarClienteIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_buscarClienteIDActionPerformed
        try {
            int id = Integer.parseInt(jT_idCliente.getText());
            Cliente clienteEncontrado = cliData.buscarClientePorId(id);
            if (clienteEncontrado != null) {
                String nomb = clienteEncontrado.getNombre();
                jT_mostrarNombreCliente.setText(nomb);
            } else {
                JOptionPane.showMessageDialog(this, "Cliente no encontrado.");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al buscar." + ex.getMessage());
        }
    }//GEN-LAST:event_jB_buscarClienteIDActionPerformed

    private void jB_OkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_OkActionPerformed
        try {
            int idProducto = Integer.parseInt(jT_IDProducto.getText());
            Producto productoEncontrado = proData.buscarProductoPorId(idProducto);
            if (productoEncontrado != null) {
                String nom = productoEncontrado.getNombreProducto();
                double precio = productoEncontrado.getPrecioActual();
                jT_MostrarNombreProducto.setText(nom);
                jT_MostrarPrecioProducto.setText(String.valueOf(precio));
            } else {
                JOptionPane.showMessageDialog(this, "Producto no encontrado.");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al buscar Producto." + ex.getMessage());
        }

    }//GEN-LAST:event_jB_OkActionPerformed

    private void jB_VenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_VenderActionPerformed
        try {
            //REGISTRAR VENTA
            int idCliente = Integer.parseInt(jT_idCliente.getText());
            SimpleDateFormat ff = new SimpleDateFormat("dd/MM/yyyy");
            ff.format(jC_fechaCompra.getCalendar().getTime());
            LocalDate fechaCompra = jC_fechaCompra.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            Venta vent = new Venta(idCliente, fechaCompra);
            ventaData.registrarVenta(vent);

            int idProducto = Integer.parseInt(jT_IDProducto.getText());
            int cantidad = Integer.parseInt(jT_CantidadDeVenta.getText());

            boolean stockSuficiente = proData.verificarStockSuficiente(idProducto, cantidad);
            if (stockSuficiente) {
                proData.restarStock(idProducto, cantidad);
                llenarCabeceraProductos();
                jT_MostrarIdProducto_vender.setText(String.valueOf(idProducto));

                // Esto habilita el boton "AgregarDetallesVenta" si hay suficiente stock
                jB_AgregarDetallesVenta.setEnabled(true);
            } else {
                mostrarAlerta("No hay stock del producto.");

                // Esto deshabilita el boton "AgregarDetallesVenta" si no hay suficiente stock
                jB_AgregarDetallesVenta.setEnabled(false);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al registrar Venta: " + ex.getMessage());
        }
    }//GEN-LAST:event_jB_VenderActionPerformed

    private void jB_AgregarDetallesVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_AgregarDetallesVentaActionPerformed
        // TODO add your handling code here:
        try {
            llenarTablaIdVenta();
            int cantidad = Integer.parseInt(jT_CantidadDeVenta.getText());
            double precio = Double.parseDouble(jT_MostrarPrecioProducto.getText());
            int idpro = Integer.parseInt(jT_IDProducto.getText());
            DetalleVenta ventaDetalle = new DetalleVenta(cantidad, idVenta, precio, idpro);
            DetalleVentaData ventaDetalleda = new DetalleVentaData();
            ventaDetalleda.agregarDetalleVenta(ventaDetalle);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al Guardar detalle de venta." + ex.getMessage());
        }
    }//GEN-LAST:event_jB_AgregarDetallesVentaActionPerformed

    private void jB_HistorialDeVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_HistorialDeVentasActionPerformed
        dispose();
        vistaDetalleVenta ventaDetalle = new vistaDetalleVenta();
        ventaDetalle.setVisible(true);
    }//GEN-LAST:event_jB_HistorialDeVentasActionPerformed

    private void HomeBtnTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeBtnTxtMouseClicked
        dispose();
        principalMenu menu = new principalMenu();
        menu.setVisible(true);
    }//GEN-LAST:event_HomeBtnTxtMouseClicked

    private void HomeBtnTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeBtnTxtMouseEntered
        HomeBtn.setBackground(Color.MAGENTA);
    }//GEN-LAST:event_HomeBtnTxtMouseEntered

    private void HomeBtnTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeBtnTxtMouseExited
        HomeBtn.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_HomeBtnTxtMouseExited

    private void BtnExitTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnExitTxtMouseClicked
        int option = JOptionPane.showConfirmDialog(this, "¿Estás seguro de que queres cerrar el programa?", "Confirmar cierre", JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_BtnExitTxtMouseClicked

    private void BtnExitTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnExitTxtMouseEntered
        BtnExit.setBackground(Color.RED);
    }//GEN-LAST:event_BtnExitTxtMouseEntered

    private void BtnExitTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnExitTxtMouseExited
        BtnExit.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_BtnExitTxtMouseExited

    private void jP_headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_headerMouseDragged
        //Esto hace que se pueda draggear el programa
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jP_headerMouseDragged

    private void jP_headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jP_headerMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaVenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BtnExit;
    private javax.swing.JLabel BtnExitTxt;
    private javax.swing.JPanel HomeBtn;
    private javax.swing.JLabel HomeBtnTxt;
    private javax.swing.JLabel JL_LOGO;
    private javax.swing.JButton jB_AgregarDetallesVenta;
    private javax.swing.JButton jB_HistorialDeVentas;
    private javax.swing.JButton jB_Ok;
    private javax.swing.JButton jB_Vender;
    private javax.swing.JButton jB_buscarClienteID;
    private com.toedter.calendar.JDateChooser jC_fechaCompra;
    private javax.swing.JLabel jL_Cantidad;
    private javax.swing.JLabel jL_FechaCompra;
    private javax.swing.JLabel jL_PrecioVenta;
    private javax.swing.JLabel jL_ProductoId;
    private javax.swing.JLabel jL_Titulo;
    private javax.swing.JLabel jL_TituloDetalleDeVenta;
    private javax.swing.JLabel jL_idCliente;
    private javax.swing.JLabel jL_nombreDelProducto;
    private javax.swing.JLabel jL_tituloTablaClientes;
    private javax.swing.JLabel jL_tituloTablaProductos;
    private javax.swing.JLabel jL_ultimoIdVenta;
    private javax.swing.JLabel jL_ultimoProductoID;
    private javax.swing.JPanel jP_header;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jS_LineaSeparadora;
    private javax.swing.JSeparator jS_LineaSeparadora2;
    private javax.swing.JScrollPane jS_mostrarClientes;
    private javax.swing.JScrollPane jS_tablaProductos;
    private javax.swing.JScrollPane jS_ultimoIdVenta;
    private javax.swing.JTextField jT_CantidadDeVenta;
    private javax.swing.JTextField jT_IDProducto;
    private javax.swing.JTable jT_IdVenta;
    private javax.swing.JTextField jT_MostrarIdProducto_vender;
    private javax.swing.JTextField jT_MostrarNombreProducto;
    private javax.swing.JTextField jT_MostrarPrecioProducto;
    private javax.swing.JTextField jT_idCliente;
    private javax.swing.JTable jT_mostrarClientes;
    private javax.swing.JTextField jT_mostrarNombreCliente;
    private javax.swing.JTable jT_mostrarProductos;
    // End of variables declaration//GEN-END:variables

    private void armarCabeceracliente() {
        ArrayList titulos = new ArrayList();
        titulos.add("ID");
        titulos.add("Apellido");
        titulos.add("Nombre");
        modelo = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                titulos.add("ID");
                titulos.add("Apellido");
                titulos.add("Nombre");
                return false;
            }

        };
        for (Object titulo : titulos) {
            modelo.addColumn(titulo);
            jT_mostrarClientes.setModel(modelo);
        }
    }

    private void llenarCabeceraCliente() {
        List<Cliente> clien = cliData.obtenerClientes();
        for (Cliente cliente : clien) {
            modelo.addRow(new Object[]{cliente.getIdCliente(), cliente.getNombre(), cliente.getApellido()});
        }
    }

    private void armarCabeceraProductos() {
        ArrayList titulos = new ArrayList();
        titulos.add("ID");
        titulos.add("Nombre");
        titulos.add("Descripcion");
        titulos.add("Precio");
        titulos.add("Stock");
        modeloproducto = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                titulos.add("ID");
                titulos.add("Nombre");
                titulos.add("Descripcion");
                titulos.add("Precio");
                titulos.add("Stock");
                return false;
            }
        };
        for (Object titulo : titulos) {
            modeloproducto.addColumn(titulo);
            jT_mostrarProductos.setModel(modeloproducto);
        }

    }

    private void llenarCabeceraProductos() {
        List<Producto> produc = proData.obtenerProductos();
        for (Producto producto : produc) {
            modeloproducto.addRow(new Object[]{producto.getIdProducto(), producto.getNombreProducto(), producto.getDescripcion(), producto.getPrecioActual(), producto.getStock()});
        }
    }

    private void armarCabeceraIdVenta() {
        ArrayList titulos = new ArrayList();
        titulos.add("ID");
        modeloidVenta = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                titulos.add("ID");
                return false;
            }
        };
        for (Object titulo : titulos) {
            modeloidVenta.addColumn(titulo);
            jT_IdVenta.setModel(modeloidVenta);
        }

    }

    private void llenarTablaIdVenta() {
        modeloidVenta.setRowCount(0);
        idVenta = ventaData.obtenerUltimoIddeVenta();
        modeloidVenta.addRow(new Object[]{idVenta});
    }
}
