/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista.menuPrincipal;

import Control.ProveedorData;
import Modelo.Proveedor;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hugo
 */
public class vistaProveedor extends javax.swing.JFrame {
    private ProveedorData proData = new ProveedorData();
    private DefaultTableModel modelo = new DefaultTableModel();
    /**
     * Creates new form vistaProveedor
     */
    public vistaProveedor() {
        initComponents();
        armarCabecera();
        borrarTabla();
        llenarTabla();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jT_iDProveedor = new javax.swing.JTextField();
        jT_razonSocialProveedor = new javax.swing.JTextField();
        jT_domicilioProveedor = new javax.swing.JTextField();
        jT_telefonoProveedor = new javax.swing.JTextField();
        jB_buscar = new javax.swing.JButton();
        jB_agregarProveedor = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jT_tablaProveedor = new javax.swing.JTable();
        jB_editarProveedor = new javax.swing.JButton();
        jB_eliminarProveedor = new javax.swing.JButton();
        jB_limpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Proveedor");

        jLabel2.setText("iD Proveedor");

        jLabel3.setText("Razon Social");

        jLabel4.setText("Domicilio");

        jLabel5.setText("Telefono");

        jT_iDProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_iDProveedorActionPerformed(evt);
            }
        });

        jB_buscar.setText("Buscar");
        jB_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_buscarActionPerformed(evt);
            }
        });

        jB_agregarProveedor.setText("Agregar ");
        jB_agregarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_agregarProveedorActionPerformed(evt);
            }
        });

        jT_tablaProveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Titulo 1", "Titulo 2", "Titulo 3", "Titulo 4"
            }
        ));
        jScrollPane1.setViewportView(jT_tablaProveedor);

        jB_editarProveedor.setText("Editar");
        jB_editarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_editarProveedorActionPerformed(evt);
            }
        });

        jB_eliminarProveedor.setText("Eliminar");
        jB_eliminarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_eliminarProveedorActionPerformed(evt);
            }
        });

        jB_limpiar.setText("Limpiar");
        jB_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_limpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jB_limpiar)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jB_agregarProveedor)
                                .addGap(18, 18, 18)
                                .addComponent(jB_editarProveedor)
                                .addGap(18, 18, 18)
                                .addComponent(jB_eliminarProveedor))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(310, 310, 310)
                                .addComponent(jB_buscar)
                                .addGap(16, 16, 16))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(105, 105, 105)
                                        .addComponent(jT_domicilioProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(110, 110, 110)
                                        .addComponent(jT_telefonoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(90, 90, 90)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jT_razonSocialProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jT_iDProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jT_iDProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_buscar))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jT_razonSocialProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jT_domicilioProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jT_telefonoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_limpiar))
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_agregarProveedor)
                    .addComponent(jB_editarProveedor)
                    .addComponent(jB_eliminarProveedor))
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void armarCabecera(){
        ArrayList titulos= new ArrayList();
        titulos.add("ID");
        titulos.add("Razon Social");
        titulos.add("Domicilio");
        titulos.add("Telefono");
        modelo = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
            titulos.add("ID");
            titulos.add("Razon Social");
            titulos.add("Domicilio");
            titulos.add("Telefono");
            return false;
        }
            
        };
        for (Object titulo : titulos) {
            modelo.addColumn(titulo);
            jT_tablaProveedor.setModel(modelo);
        }
        
    }
    public void llenarTabla() {
    List<Proveedor> proveedores = proData.obtenerProveedores();
    for (Proveedor proveedor : proveedores) {
        modelo.addRow(new Object[]{proveedor.getIdProveedor(), proveedor.getRazonSocial(), proveedor.getDomicilio(), proveedor.getTelefono()});
    }
}
    private void borrarTabla(){
    int filas= modelo.getRowCount()-1;
    for (int i = filas; i >=0; i--) {
        modelo.removeRow(i);
    }
}
    private void limpiar(){
        jT_domicilioProveedor.setText("");
        jT_iDProveedor.setText("");
        jT_razonSocialProveedor.setText("");
        jT_telefonoProveedor.setText("");
       
    }
    private void jB_agregarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_agregarProveedorActionPerformed
        // TODO add your handling code here:
        
        
        try{
            String razon = jT_razonSocialProveedor.getText();
            String dom = jT_domicilioProveedor.getText();
            String tel = jT_telefonoProveedor.getText();
            long telF = 0;
            telF = Long.parseLong(tel);
            Proveedor pro = new Proveedor(razon, dom, tel);
            proData.agregarProveedor(pro);
            JOptionPane.showMessageDialog(this, "Proveedor Guardado.");
            borrarTabla();
            llenarTabla();
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Error el Agregar Proveedor."+ex.getMessage());
        }
    }//GEN-LAST:event_jB_agregarProveedorActionPerformed

    private void jT_iDProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_iDProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_iDProveedorActionPerformed

    private void jB_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_buscarActionPerformed
        // TODO add your handling code here:
        try{
          int id = Integer.parseInt(jT_iDProveedor.getText());
          Proveedor proEncontrado = proData.buscarProveedor(id);
          if(proEncontrado != null){
              String razon = proEncontrado.getRazonSocial();
              String dom = proEncontrado.getDomicilio();
              String tel = proEncontrado.getTelefono();
              jT_razonSocialProveedor.setText(razon);
              jT_domicilioProveedor.setText(dom);
              jT_telefonoProveedor.setText(tel);
          }else{
              JOptionPane.showMessageDialog(this, "Proveedor no encontrado.");
              //Agregar limpiar.
          }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Error al buscar."+ex.getMessage());
        }
    }//GEN-LAST:event_jB_buscarActionPerformed

    private void jB_eliminarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_eliminarProveedorActionPerformed
        // TODO add your handling code here:
       try{
           int id = Integer.parseInt(jT_iDProveedor.getText());
           proData.eliminarProveedor(id);
           JOptionPane.showMessageDialog(this, "Proveedor eliminado.");
           borrarTabla();
            llenarTabla();
            limpiar();
           //Agregar Limpiar.
       }catch(Exception ex){
           JOptionPane.showMessageDialog(this, "Error al Eliminar proveedor."+ex.getMessage());
       }
        
    }//GEN-LAST:event_jB_eliminarProveedorActionPerformed

    private void jB_editarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_editarProveedorActionPerformed
        // TODO add your handling code here:
        try{
            int id = Integer.parseInt(jT_iDProveedor.getText());
            String razon = jT_razonSocialProveedor.getText();
            String dom = jT_domicilioProveedor.getText();
            String tel = jT_telefonoProveedor.getText();
            Proveedor pro = new Proveedor(id, razon, dom, tel);
            proData.modificarProveedor(pro);
            JOptionPane.showMessageDialog(this, "Proveedor Modificado.");
            borrarTabla();
            llenarTabla();
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Error el Modificar proveedor."+ex.getMessage());
        }
    }//GEN-LAST:event_jB_editarProveedorActionPerformed

    private void jB_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_limpiarActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_jB_limpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaProveedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_agregarProveedor;
    private javax.swing.JButton jB_buscar;
    private javax.swing.JButton jB_editarProveedor;
    private javax.swing.JButton jB_eliminarProveedor;
    private javax.swing.JButton jB_limpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jT_domicilioProveedor;
    private javax.swing.JTextField jT_iDProveedor;
    private javax.swing.JTextField jT_razonSocialProveedor;
    private javax.swing.JTable jT_tablaProveedor;
    private javax.swing.JTextField jT_telefonoProveedor;
    // End of variables declaration//GEN-END:variables
}
