/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista.menuPrincipal;

import Control.ClienteData;
import Control.DetalleVentaData;
import Control.ProductoData;
import Control.VentaData;
import Modelo.Cliente;
import Modelo.DetalleVenta;
import Modelo.Producto;
import Modelo.Venta;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hugo
 */
public class vistaVenta extends javax.swing.JFrame {
    private DefaultTableModel modelo = new DefaultTableModel();
    private DefaultTableModel modeloproducto = new DefaultTableModel();
    private DefaultTableModel modeloidProducto= new DefaultTableModel();
    private DefaultTableModel modeloidVenta= new DefaultTableModel();
    private VentaData ventaData = new VentaData();
    private ClienteData cliData = new ClienteData();
    private ProductoData proData = new ProductoData();
    private int idVenta;
    private int idProducto;
    /**
     * Creates new form vistaVenta
     */
    public vistaVenta() {
        initComponents();
        armarCabeceracliente();
        llenarCabeceraCliente();
        armarCabeceraProductos();
        llenarCabeceraProductos();
        armarCabeceraIdVenta();
//        armarCabceraIdProducto();
        llenarTablaIdVenta();
//        llenarTablaIdProducto();
    }
    private void llenarIdVenta(){
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jT_idCliente = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jT_mostrarClientes = new javax.swing.JTable();
        jT_mostrarNombreCliente = new javax.swing.JTextField();
        jB_buscarClienteID = new javax.swing.JButton();
        jC_fechaCompra = new com.toedter.calendar.JCalendar();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jT_MostrarNombreProducto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jT_CantidadDeVenta = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jT_MostrarPrecioProducto = new javax.swing.JTextField();
        jB_Vender = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jT_mostrarProductos = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jT_IDProducto = new javax.swing.JTextField();
        jB_AgregarDetallesVenta = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jB_Ok = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jT_mostrarFecha = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jT_IdVenta = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jT_MostrarIdProducto_vender = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Venta");

        jLabel2.setText("Id Cliente");

        jT_mostrarClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jT_mostrarClientes);

        jT_mostrarNombreCliente.setEditable(false);

        jB_buscarClienteID.setText("Buscar");
        jB_buscarClienteID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_buscarClienteIDActionPerformed(evt);
            }
        });

        jC_fechaCompra.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jC_fechaCompraPropertyChange(evt);
            }
        });

        jLabel3.setText("Fecha de Compra");

        jLabel4.setText("Detalle de Venta");

        jLabel5.setText("Nombre del Producto");

        jT_MostrarNombreProducto.setEditable(false);

        jLabel6.setText("Cantidad");

        jLabel7.setText("Precio Venta");

        jT_MostrarPrecioProducto.setEditable(false);

        jB_Vender.setText("Vender");
        jB_Vender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_VenderActionPerformed(evt);
            }
        });

        jT_mostrarProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jT_mostrarProductos);

        jLabel8.setText("Productos");

        jLabel9.setText("IdProducto");

        jB_AgregarDetallesVenta.setText("Guardar Detalles de Venta");
        jB_AgregarDetallesVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_AgregarDetallesVentaActionPerformed(evt);
            }
        });

        jButton4.setText("Historial de Ventas");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jB_Ok.setText("Ok");
        jB_Ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_OkActionPerformed(evt);
            }
        });

        jLabel10.setText("Clientes");

        jT_mostrarFecha.setEditable(false);

        jT_IdVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jT_IdVenta);

        jLabel11.setText("Id Venta");

        jLabel12.setText("Id Producto");

        jT_MostrarIdProducto_vender.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(61, 61, 61)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jT_mostrarNombreCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                            .addComponent(jT_idCliente))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jB_buscarClienteID))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jT_MostrarNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel9)
                                            .addGap(18, 18, 18)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel4)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jT_IDProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jB_Ok)))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(jT_CantidadDeVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(44, 44, 44)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jB_AgregarDetallesVenta)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(jLabel11)
                                                            .addComponent(jLabel12))
                                                        .addGap(18, 18, 18)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jT_MostrarIdProducto_vender, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addGap(33, 33, 33))))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jT_MostrarPrecioProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jB_Vender)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jC_fechaCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addComponent(jT_mostrarFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(136, 136, 136))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(163, 163, 163))))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(263, 263, 263)
                .addComponent(jButton4)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jT_MostrarPrecioProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel2)
                                            .addComponent(jT_idCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jB_buscarClienteID))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jT_mostrarNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jC_fechaCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(136, 136, 136)
                                .addComponent(jT_mostrarFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(jT_IDProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jB_Ok))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(jT_MostrarNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jT_CantidadDeVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel7))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jB_Vender)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jT_MostrarIdProducto_vender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jB_AgregarDetallesVenta))
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jB_buscarClienteIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_buscarClienteIDActionPerformed
        // TODO add your handling code here:
        try{
           int id = Integer.parseInt(jT_idCliente.getText());
           Cliente clienteEncontrado = cliData.buscarClientePorId(id);
           if(clienteEncontrado!=null){
               String nomb = clienteEncontrado.getNombre();
               jT_mostrarNombreCliente.setText(nomb);
           }else{
               JOptionPane.showMessageDialog(this, "Cliente no encontrado.");
           }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Error al buscar."+ex.getMessage());
        }
    }//GEN-LAST:event_jB_buscarClienteIDActionPerformed

    private void jB_OkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_OkActionPerformed
        // TODO add your handling code here:
        try{
            int idProducto = Integer.parseInt(jT_IDProducto.getText());
            Producto productoEncontrado = proData.buscarProductoPorId(idProducto);
            if(productoEncontrado!= null){
                String nom = productoEncontrado.getNombreProducto();
                double precio =  productoEncontrado.getPrecioActual();
                jT_MostrarNombreProducto.setText(nom);
                jT_MostrarPrecioProducto.setText(String.valueOf(precio));
            }else{
                JOptionPane.showMessageDialog(this, "Producto no encontrado.");
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Error al buscar Producto."+ex.getMessage());
        }
        
    }//GEN-LAST:event_jB_OkActionPerformed

    private void jB_VenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_VenderActionPerformed
        // TODO add your handling code here:
        try{
            //REGISTRAR VENTA
            int idCliente = Integer.parseInt(jT_idCliente.getText());
            SimpleDateFormat ff= new SimpleDateFormat("dd/MM/yyyy");
            ff.format(jC_fechaCompra.getCalendar().getTime());
            LocalDate fechaCompra = jC_fechaCompra.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            Venta vent = new Venta(idCliente, fechaCompra);
            ventaData.registrarVenta(vent);
            try{
                //MODIFICAR PRODUCTO
                int idProducto = Integer.parseInt(jT_IDProducto.getText());
                int cantidad = Integer.parseInt(jT_CantidadDeVenta.getText());
                proData.restarStock(idProducto, cantidad);
                llenarCabeceraProductos();
                jT_MostrarIdProducto_vender.setText(String.valueOf(idProducto));
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, "Error al modificar Producto."+e.getMessage());
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Error registar Venta."+ex.getMessage());
        }
    }//GEN-LAST:event_jB_VenderActionPerformed

    private void jC_fechaCompraPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jC_fechaCompraPropertyChange
        // TODO add your handling code here:
        if(evt.getOldValue()!=null){
            SimpleDateFormat ff = new SimpleDateFormat("dd/MM/yyyy");
            jT_mostrarFecha.setText(ff.format(jC_fechaCompra.getCalendar().getTime()));
        }
    }//GEN-LAST:event_jC_fechaCompraPropertyChange

    private void jB_AgregarDetallesVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_AgregarDetallesVentaActionPerformed
        // TODO add your handling code here:
        try{
            llenarTablaIdVenta();
            int cantidad = Integer.parseInt(jT_CantidadDeVenta.getText());
            double precio = Double.parseDouble(jT_MostrarPrecioProducto.getText());
            int idpro = Integer.parseInt(jT_IDProducto.getText());
            DetalleVenta ventaDetalle = new DetalleVenta(cantidad, idVenta, precio, idpro);
            DetalleVentaData ventaDetalleda= new DetalleVentaData();
            ventaDetalleda.agregarDetalleVenta(ventaDetalle);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Error al Guardar detalle de venta."+ex.getMessage());
        }
        
    }//GEN-LAST:event_jB_AgregarDetallesVentaActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        dispose();
        vistaDetalleVenta ventaDetalle = new vistaDetalleVenta();
        ventaDetalle.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaVenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_AgregarDetallesVenta;
    private javax.swing.JButton jB_Ok;
    private javax.swing.JButton jB_Vender;
    private javax.swing.JButton jB_buscarClienteID;
    private javax.swing.JButton jButton4;
    private com.toedter.calendar.JCalendar jC_fechaCompra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jT_CantidadDeVenta;
    private javax.swing.JTextField jT_IDProducto;
    private javax.swing.JTable jT_IdVenta;
    private javax.swing.JTextField jT_MostrarIdProducto_vender;
    private javax.swing.JTextField jT_MostrarNombreProducto;
    private javax.swing.JTextField jT_MostrarPrecioProducto;
    private javax.swing.JTextField jT_idCliente;
    private javax.swing.JTable jT_mostrarClientes;
    private javax.swing.JTextField jT_mostrarFecha;
    private javax.swing.JTextField jT_mostrarNombreCliente;
    private javax.swing.JTable jT_mostrarProductos;
    // End of variables declaration//GEN-END:variables

    private void armarCabeceracliente() {
        ArrayList titulos= new ArrayList();
        titulos.add("ID");
        titulos.add("Apellido");
        titulos.add("Nombre");
        modelo = new DefaultTableModel(){
        @Override
        public boolean isCellEditable(int row, int column){
            titulos.add("ID");
            titulos.add("Apellido");
            titulos.add("Nombre");
        return false;
    }
       
    };
        for (Object titulo : titulos) {
            modelo.addColumn(titulo);
            jT_mostrarClientes.setModel(modelo);
        }
    }

    private void llenarCabeceraCliente() {
        List<Cliente> clien = cliData.obtenerClientes();
        for (Cliente cliente : clien){
            modelo.addRow(new Object[]{cliente.getIdCliente(),cliente.getNombre(),cliente.getApellido()});
        }
    }

    private void armarCabeceraProductos() {
        ArrayList titulos = new ArrayList();
        titulos.add("ID");
        titulos.add("Nombre");
        titulos.add("Descripcion");
        titulos.add("Precio");
        titulos.add("Stock");
        modeloproducto = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row,int column){
                titulos.add("ID");
                titulos.add("Nombre");
                titulos.add("Descripcion");
                titulos.add("Precio");
                titulos.add("Stock");
                return false;
            }
        };
        for (Object titulo : titulos) {
            modeloproducto.addColumn(titulo);
            jT_mostrarProductos.setModel(modeloproducto);
        }
        
    }

    private void llenarCabeceraProductos() {
        List<Producto> produc = proData.obtenerProductos();
        for (Producto producto : produc) {
            modeloproducto.addRow(new Object[]{producto.getIdProducto(),producto.getNombreProducto(),producto.getDescripcion(),producto.getPrecioActual(),producto.getStock()});
        }
    }

    private void armarCabeceraIdVenta() {
        ArrayList titulos = new ArrayList();
        titulos.add("ID");
        modeloidVenta = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row,int column){
              titulos.add("ID");  
              return false;
            }
        };
        for (Object titulo : titulos) {
            modeloidVenta.addColumn(titulo);
            jT_IdVenta.setModel(modeloidVenta);
        }
        
     }

//    private void armarCabceraIdProducto() {
//        ArrayList titulos = new ArrayList();
//        titulos.add("ID");
//        modeloidProducto = new DefaultTableModel(){
//            @Override
//            public boolean isCellEditable(int row,int column){
//              titulos.add("ID");  
//              return false;
//            }
//        };
//        for (Object titulo : titulos) {
//            modeloidProducto.addColumn(titulo);
//            jT_IdProducto.setModel(modeloidProducto);
//        }
//    }

    private void llenarTablaIdVenta() {
        modeloidVenta.setRowCount(0);
         idVenta = ventaData.obtenerUltimoIddeVenta();
         modeloidVenta.addRow(new Object[]{idVenta});
    }

//    private void llenarTablaIdProducto() {
//        modeloidProducto.setRowCount(0);
//        int idProducto = Integer.parseInt(jT_IDProducto.getText());
//        Object[] fila = {idProducto};
//        modeloidProducto.addRow(fila);
//    }
}
