/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista.menuPrincipal;

import Control.CompraData;
import Control.DetalleCompraData;
import Control.ProductoData;
import Control.ProveedorData;
import Modelo.Compra;
import Modelo.DetalleCompra;
import Modelo.Producto;
import Modelo.Proveedor;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hugo, APOLO
 */
public class vistaCompra extends javax.swing.JFrame {

    private DefaultTableModel modelo = new DefaultTableModel();
    private DefaultTableModel modeloCompra = new DefaultTableModel();
    private ProveedorData proveData = new ProveedorData();
    private CompraData comData = new CompraData();
    private ProductoData proData = new ProductoData();
    private DetalleCompraData detalleData = new DetalleCompraData();

    private int idCompra;
    private int idProducto;

    /**
     * Creates new form vistaCompra
     */
    int xMouse, yMouse;

    public vistaCompra() {
        initComponents();
        armarCabecera();
        llenarTabla();
        cabeceraIdCompra();
        llenarIdCompra();
        cabeceraIdProducto();
        llenarIdProducto();
        actualizarIdTodo();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jP_header = new javax.swing.JPanel();
        HomeBtn = new javax.swing.JPanel();
        HomeBtnTxt = new javax.swing.JLabel();
        BtnExit = new javax.swing.JPanel();
        BtnExitTxt = new javax.swing.JLabel();
        JL_LOGO = new javax.swing.JLabel();
        jL_Titulo = new javax.swing.JLabel();
        jS_LineaSeparadora = new javax.swing.JSeparator();
        jL_IDProveedor = new javax.swing.JLabel();
        jT_idProveedor_Compra = new javax.swing.JTextField();
        jB_buscarProveedor_compra = new javax.swing.JButton();
        jT_mostrarProveedor_compra = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jT_TablaProductos = new javax.swing.JTable();
        jS_LineaSeparadora2 = new javax.swing.JSeparator();
        jL_DetalleDeCompra = new javax.swing.JLabel();
        jL_NombreDelProducto = new javax.swing.JLabel();
        jT_nombreProducto_DetalleCompra = new javax.swing.JTextField();
        jL_Cantidad = new javax.swing.JLabel();
        jT_cantidad_DetalleCompra = new javax.swing.JTextField();
        jL_PrecioCosto = new javax.swing.JLabel();
        jT_precioCosto_DetalleCompra = new javax.swing.JTextField();
        jL_Descripcion = new javax.swing.JLabel();
        jT_descripcion_DetalleCompra = new javax.swing.JTextField();
        jL_FechaDeCompra = new javax.swing.JLabel();
        jC_FechaCompra = new com.toedter.calendar.JDateChooser();
        jL_CargarDetalle = new javax.swing.JLabel();
        jL_IdCompraTabla = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jT_idCompra_mostrar = new javax.swing.JTable();
        jL_IdProductoTabla = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jT_idProdcuto_mostrar = new javax.swing.JTable();
        jB_compra = new javax.swing.JButton();
        jB_guardarDetalle = new javax.swing.JButton();
        jB_historialCompra = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(800, 700));
        setMinimumSize(new java.awt.Dimension(800, 700));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setMaximumSize(new java.awt.Dimension(800, 700));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 700));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 700));

        jP_header.setBackground(new java.awt.Color(51, 51, 51));
        jP_header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jP_headerMouseDragged(evt);
            }
        });
        jP_header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jP_headerMousePressed(evt);
            }
        });

        HomeBtn.setBackground(new java.awt.Color(51, 51, 51));

        HomeBtnTxt.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        HomeBtnTxt.setForeground(new java.awt.Color(255, 255, 255));
        HomeBtnTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HomeBtnTxt.setText("<");
        HomeBtnTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HomeBtnTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeBtnTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HomeBtnTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HomeBtnTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout HomeBtnLayout = new javax.swing.GroupLayout(HomeBtn);
        HomeBtn.setLayout(HomeBtnLayout);
        HomeBtnLayout.setHorizontalGroup(
            HomeBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 92, Short.MAX_VALUE)
            .addGroup(HomeBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(HomeBtnLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(HomeBtnTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        HomeBtnLayout.setVerticalGroup(
            HomeBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(HomeBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(HomeBtnLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(HomeBtnTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        BtnExit.setBackground(new java.awt.Color(51, 51, 51));
        BtnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        BtnExitTxt.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        BtnExitTxt.setForeground(new java.awt.Color(255, 255, 255));
        BtnExitTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtnExitTxt.setText("X");
        BtnExitTxt.setMaximumSize(new java.awt.Dimension(70, 70));
        BtnExitTxt.setMinimumSize(new java.awt.Dimension(70, 70));
        BtnExitTxt.setPreferredSize(new java.awt.Dimension(70, 70));
        BtnExitTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnExitTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnExitTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnExitTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout BtnExitLayout = new javax.swing.GroupLayout(BtnExit);
        BtnExit.setLayout(BtnExitLayout);
        BtnExitLayout.setHorizontalGroup(
            BtnExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BtnExitLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnExitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        BtnExitLayout.setVerticalGroup(
            BtnExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnExitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtnExitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JL_LOGO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagenes/LOGOCHIQUITO.png"))); // NOI18N
        JL_LOGO.setText("jLabel2");

        javax.swing.GroupLayout jP_headerLayout = new javax.swing.GroupLayout(jP_header);
        jP_header.setLayout(jP_headerLayout);
        jP_headerLayout.setHorizontalGroup(
            jP_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_headerLayout.createSequentialGroup()
                .addComponent(HomeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 211, Short.MAX_VALUE)
                .addComponent(JL_LOGO, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(212, 212, 212)
                .addComponent(BtnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jP_headerLayout.setVerticalGroup(
            jP_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BtnExit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jP_headerLayout.createSequentialGroup()
                .addGroup(jP_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(HomeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JL_LOGO, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jL_Titulo.setFont(new java.awt.Font("HP Simplified", 1, 24)); // NOI18N
        jL_Titulo.setForeground(new java.awt.Color(204, 0, 204));
        jL_Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_Titulo.setText("COMPRAS");

        jL_IDProveedor.setFont(new java.awt.Font("HP Simplified", 1, 15)); // NOI18N
        jL_IDProveedor.setForeground(new java.awt.Color(255, 255, 255));
        jL_IDProveedor.setText("ID PROVEEDOR");

        jT_idProveedor_Compra.setFont(new java.awt.Font("HP Simplified", 1, 15)); // NOI18N

        jB_buscarProveedor_compra.setFont(new java.awt.Font("HP Simplified", 1, 15)); // NOI18N
        jB_buscarProveedor_compra.setText("BUSCAR");
        jB_buscarProveedor_compra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jB_buscarProveedor_compra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_buscarProveedor_compraActionPerformed(evt);
            }
        });

        jT_mostrarProveedor_compra.setEditable(false);
        jT_mostrarProveedor_compra.setFont(new java.awt.Font("HP Simplified", 1, 15)); // NOI18N
        jT_mostrarProveedor_compra.setForeground(new java.awt.Color(204, 0, 204));
        jT_mostrarProveedor_compra.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jT_TablaProductos.setFont(new java.awt.Font("HP Simplified", 0, 15)); // NOI18N
        jT_TablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jT_TablaProductos.setSelectionBackground(new java.awt.Color(204, 0, 204));
        jScrollPane1.setViewportView(jT_TablaProductos);

        jL_DetalleDeCompra.setFont(new java.awt.Font("HP Simplified", 1, 24)); // NOI18N
        jL_DetalleDeCompra.setForeground(new java.awt.Color(255, 255, 255));
        jL_DetalleDeCompra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_DetalleDeCompra.setText("DETALLE DE COMPRA");

        jL_NombreDelProducto.setFont(new java.awt.Font("HP Simplified", 1, 15)); // NOI18N
        jL_NombreDelProducto.setForeground(new java.awt.Color(255, 255, 255));
        jL_NombreDelProducto.setText("NOMBRE DEL PRODUCTO");

        jT_nombreProducto_DetalleCompra.setFont(new java.awt.Font("HP Simplified", 1, 15)); // NOI18N

        jL_Cantidad.setFont(new java.awt.Font("HP Simplified", 1, 15)); // NOI18N
        jL_Cantidad.setForeground(new java.awt.Color(255, 255, 255));
        jL_Cantidad.setText("CANTIDAD");

        jT_cantidad_DetalleCompra.setFont(new java.awt.Font("HP Simplified", 1, 15)); // NOI18N
        jT_cantidad_DetalleCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_cantidad_DetalleCompraActionPerformed(evt);
            }
        });

        jL_PrecioCosto.setFont(new java.awt.Font("HP Simplified", 1, 15)); // NOI18N
        jL_PrecioCosto.setForeground(new java.awt.Color(255, 255, 255));
        jL_PrecioCosto.setText("PRECIO COSTO");

        jT_precioCosto_DetalleCompra.setFont(new java.awt.Font("HP Simplified", 1, 15)); // NOI18N
        jT_precioCosto_DetalleCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_precioCosto_DetalleCompraActionPerformed(evt);
            }
        });

        jL_Descripcion.setFont(new java.awt.Font("HP Simplified", 1, 15)); // NOI18N
        jL_Descripcion.setForeground(new java.awt.Color(255, 255, 255));
        jL_Descripcion.setText("DESCRIPCION");

        jT_descripcion_DetalleCompra.setFont(new java.awt.Font("HP Simplified", 1, 15)); // NOI18N

        jL_FechaDeCompra.setFont(new java.awt.Font("HP Simplified", 1, 15)); // NOI18N
        jL_FechaDeCompra.setForeground(new java.awt.Color(255, 255, 255));
        jL_FechaDeCompra.setText("FECHA DE COMPRA");

        jC_FechaCompra.setFont(new java.awt.Font("HP Simplified", 1, 15)); // NOI18N

        jL_CargarDetalle.setFont(new java.awt.Font("HP Simplified", 1, 24)); // NOI18N
        jL_CargarDetalle.setForeground(new java.awt.Color(255, 255, 255));
        jL_CargarDetalle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_CargarDetalle.setText("CARGAR DETALLE");

        jL_IdCompraTabla.setFont(new java.awt.Font("HP Simplified", 1, 15)); // NOI18N
        jL_IdCompraTabla.setForeground(new java.awt.Color(255, 255, 255));
        jL_IdCompraTabla.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_IdCompraTabla.setText("ULTIMO ID COMPRA");

        jT_idCompra_mostrar.setFont(new java.awt.Font("HP Simplified", 0, 15)); // NOI18N
        jT_idCompra_mostrar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jT_idCompra_mostrar.setSelectionBackground(new java.awt.Color(204, 0, 204));
        jScrollPane2.setViewportView(jT_idCompra_mostrar);

        jL_IdProductoTabla.setFont(new java.awt.Font("HP Simplified", 1, 15)); // NOI18N
        jL_IdProductoTabla.setForeground(new java.awt.Color(255, 255, 255));
        jL_IdProductoTabla.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_IdProductoTabla.setText("ULTIMO ID PRODUCTO");

        jT_idProdcuto_mostrar.setFont(new java.awt.Font("HP Simplified", 0, 15)); // NOI18N
        jT_idProdcuto_mostrar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jT_idProdcuto_mostrar.setSelectionBackground(new java.awt.Color(204, 0, 204));
        jScrollPane3.setViewportView(jT_idProdcuto_mostrar);

        jB_compra.setFont(new java.awt.Font("HP Simplified", 1, 15)); // NOI18N
        jB_compra.setText("COMPRAR");
        jB_compra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jB_compra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_compraActionPerformed(evt);
            }
        });

        jB_guardarDetalle.setFont(new java.awt.Font("HP Simplified", 1, 15)); // NOI18N
        jB_guardarDetalle.setText("GUARDAR DETALLES");
        jB_guardarDetalle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jB_guardarDetalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_guardarDetalleActionPerformed(evt);
            }
        });

        jB_historialCompra.setBackground(new java.awt.Color(204, 0, 204));
        jB_historialCompra.setFont(new java.awt.Font("HP Simplified", 1, 15)); // NOI18N
        jB_historialCompra.setForeground(new java.awt.Color(255, 255, 255));
        jB_historialCompra.setText("HISTORIAL DE COMPRAS");
        jB_historialCompra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jB_historialCompra.setPreferredSize(new java.awt.Dimension(179, 27));
        jB_historialCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_historialCompraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jS_LineaSeparadora)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jL_IDProveedor)
                            .addComponent(jT_mostrarProveedor_compra, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jT_idProveedor_Compra, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jB_buscarProveedor_compra))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(586, 586, 586)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jL_IdCompraTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jT_precioCosto_DetalleCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jL_PrecioCosto))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jL_Descripcion)
                                            .addComponent(jT_descripcion_DetalleCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jL_FechaDeCompra)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jT_nombreProducto_DetalleCompra)
                                            .addComponent(jL_NombreDelProducto))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jT_cantidad_DetalleCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                            .addComponent(jL_Cantidad))))
                                .addGap(297, 297, 297)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jL_IdProductoTabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jL_DetalleDeCompra)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jL_CargarDetalle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jB_historialCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jB_compra)
                                    .addComponent(jC_FechaCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jB_guardarDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(63, 63, 63))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jP_header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jL_Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jS_LineaSeparadora2)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jP_header, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jL_Titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jS_LineaSeparadora, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jL_IDProveedor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jT_idProveedor_Compra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jB_buscarProveedor_compra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addComponent(jT_mostrarProveedor_compra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(40, 40, 40)
                .addComponent(jS_LineaSeparadora2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jL_CargarDetalle)
                        .addGap(18, 18, 18)
                        .addComponent(jL_IdCompraTabla)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jL_IdProductoTabla)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jL_DetalleDeCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jL_NombreDelProducto)
                                .addGap(5, 5, 5)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jT_nombreProducto_DetalleCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jT_cantidad_DetalleCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jL_Cantidad))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jL_PrecioCosto)
                                        .addGap(3, 3, 3)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jT_precioCosto_DetalleCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jT_descripcion_DetalleCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jL_Descripcion))
                                .addGap(21, 21, 21)
                                .addComponent(jL_FechaDeCompra))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addComponent(jC_FechaCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jB_historialCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jB_compra)
                            .addComponent(jB_guardarDetalle))
                        .addGap(50, 50, 50))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jB_buscarProveedor_compraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_buscarProveedor_compraActionPerformed
        try {
            int id = Integer.parseInt(jT_idProveedor_Compra.getText());
            Proveedor proEncontrado = proveData.buscarProveedor(id);
            if (proEncontrado != null) {
                String razon = proEncontrado.getRazonSocial();
                jT_mostrarProveedor_compra.setText(razon);
            } else {
                JOptionPane.showMessageDialog(this, "Proveedor no encontrado.");
                //Agregar limpiar.
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al buscar." + ex.getMessage());
        }
    }//GEN-LAST:event_jB_buscarProveedor_compraActionPerformed

    private void jB_historialCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_historialCompraActionPerformed
        dispose();
        vistaDetalleCompra detalle = new vistaDetalleCompra();
        detalle.setVisible(true);
    }//GEN-LAST:event_jB_historialCompraActionPerformed

    private void jB_guardarDetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_guardarDetalleActionPerformed
        try {
            actualizarIdTodo();
            int cantidad = Integer.parseInt(jT_cantidad_DetalleCompra.getText());
            double precio = Double.parseDouble(jT_precioCosto_DetalleCompra.getText());

            if (cantidad < 0) {
                JOptionPane.showMessageDialog(this, "La cantidad no puede ser negativa. Por favor, ingresa un número positivo.");
                jT_cantidad_DetalleCompra.setText(""); // Limpiar el campo de texto
                jB_guardarDetalle.setEnabled(false); // Deshabilitar el botón
                return; // Detener la ejecución del método
            }

            DetalleCompra dcompra = new DetalleCompra(cantidad, precio, idCompra, idProducto);
            detalleData.agregarDetalleCompra(dcompra);
            JOptionPane.showMessageDialog(this, "Detalle Guardado correctamente.");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al guardar Detalle" + ex.getMessage());
            jB_guardarDetalle.setEnabled(false); // Deshabilitar el botón
        }
    }//GEN-LAST:event_jB_guardarDetalleActionPerformed

    private void HomeBtnTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeBtnTxtMouseClicked
        dispose();
        principalMenu menu = new principalMenu();
        menu.setVisible(true);
    }//GEN-LAST:event_HomeBtnTxtMouseClicked

    private void HomeBtnTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeBtnTxtMouseEntered
        HomeBtn.setBackground(Color.MAGENTA);
    }//GEN-LAST:event_HomeBtnTxtMouseEntered

    private void HomeBtnTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeBtnTxtMouseExited
        HomeBtn.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_HomeBtnTxtMouseExited

    private void BtnExitTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnExitTxtMouseClicked
        int option = JOptionPane.showConfirmDialog(this, "¿Estás seguro de que queres cerrar el programa?", "Confirmar cierre", JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_BtnExitTxtMouseClicked

    private void BtnExitTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnExitTxtMouseEntered
        BtnExit.setBackground(Color.RED);
    }//GEN-LAST:event_BtnExitTxtMouseEntered

    private void BtnExitTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnExitTxtMouseExited
        BtnExit.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_BtnExitTxtMouseExited

    private void jP_headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_headerMouseDragged
        //Esto hace que se pueda draggear el programa
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jP_headerMouseDragged

    private void jP_headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jP_headerMousePressed

    private void jB_compraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_compraActionPerformed
        try {
            // Registrando Compra..
            int idProveedor = Integer.parseInt(jT_idProveedor_Compra.getText());
            SimpleDateFormat ff = new SimpleDateFormat("dd/MM/yyyy");
            ff.format(jC_FechaCompra.getCalendar().getTime());
            LocalDate fechaNacimiento = jC_FechaCompra.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            Compra comp = new Compra(idProveedor, fechaNacimiento);
            comData.registrarCompra(comp);
            llenarIdCompra();

            // COMPRANDO PRODUCTO..
            String nom = jT_nombreProducto_DetalleCompra.getText();
            int cantidad = Integer.parseInt(jT_cantidad_DetalleCompra.getText());
            Double precio = Double.parseDouble(jT_precioCosto_DetalleCompra.getText());
            String descrip = jT_descripcion_DetalleCompra.getText();

            if (cantidad < 0) {
                JOptionPane.showMessageDialog(this, "La cantidad no puede ser negativa. Por favor, ingresa un número positivo.");
                jB_guardarDetalle.setEnabled(false); // Deshabilitar el botón "guardarDetalle"
                return; // Terminar la ejecución del método
            }

            if (precio < 0) {
                JOptionPane.showMessageDialog(this, "El precio no puede ser negativo. Por favor, ingresa un número positivo.");
                jB_guardarDetalle.setEnabled(false); // Deshabilitar el botón "guardarDetalle"
                return; // Terminar la ejecución del método
            }

            Producto prod = new Producto(nom, descrip, precio, cantidad, true);
            proData.agregarProducto(prod);
            llenarIdProducto();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al comprar el producto." + ex.getMessage());
            jB_guardarDetalle.setEnabled(false); // Deshabilitar el botón "guardarDetalle"
        }
    }//GEN-LAST:event_jB_compraActionPerformed

    private void jT_cantidad_DetalleCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_cantidad_DetalleCompraActionPerformed
        String input = jT_cantidad_DetalleCompra.getText();
        int cantidad = 0;

        try {
            cantidad = Integer.parseInt(input);

            // Verificar si la cantidad es negativa
            if (cantidad < 0) {
                JOptionPane.showMessageDialog(this, "La cantidad no puede ser negativa. Por favor, ingresa un número positivo.");
                jT_cantidad_DetalleCompra.setText(""); // Limpiar el campo de texto
                jB_guardarDetalle.setEnabled(false); // Deshabilitar el botón "guardarDetalle"
            } else {
                jB_guardarDetalle.setEnabled(true); // Habilitar el botón "guardarDetalle"
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingresa un número válido para la cantidad.");
            jT_cantidad_DetalleCompra.setText(""); // Limpiar el campo de texto
            jB_guardarDetalle.setEnabled(false); // Deshabilitar el botón "guardarDetalle"
        }
    }//GEN-LAST:event_jT_cantidad_DetalleCompraActionPerformed

    private void jT_precioCosto_DetalleCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_precioCosto_DetalleCompraActionPerformed
        String input = jT_precioCosto_DetalleCompra.getText();
        double precio = 0.0;

        try {
            precio = Double.parseDouble(input);

            // Verificar si el precio es negativo
            if (precio < 0) {
                JOptionPane.showMessageDialog(this, "El precio no puede ser negativo. Por favor, ingresa un número positivo.");
                jT_precioCosto_DetalleCompra.setText(""); // Limpiar el campo de texto
                jB_guardarDetalle.setEnabled(false); // Deshabilitar el botón "guardarDetalle"
            } else {
                jB_guardarDetalle.setEnabled(true); // Habilitar el botón "guardarDetalle"
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingresa un número válido para el precio.");
            jT_precioCosto_DetalleCompra.setText(""); // Limpiar el campo de texto
            jB_guardarDetalle.setEnabled(false); // Deshabilitar el botón "guardarDetalle"
        }
    }//GEN-LAST:event_jT_precioCosto_DetalleCompraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaCompra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BtnExit;
    private javax.swing.JLabel BtnExitTxt;
    private javax.swing.JPanel HomeBtn;
    private javax.swing.JLabel HomeBtnTxt;
    private javax.swing.JLabel JL_LOGO;
    private javax.swing.JButton jB_buscarProveedor_compra;
    private javax.swing.JButton jB_compra;
    private javax.swing.JButton jB_guardarDetalle;
    private javax.swing.JButton jB_historialCompra;
    private com.toedter.calendar.JDateChooser jC_FechaCompra;
    private javax.swing.JLabel jL_Cantidad;
    private javax.swing.JLabel jL_CargarDetalle;
    private javax.swing.JLabel jL_Descripcion;
    private javax.swing.JLabel jL_DetalleDeCompra;
    private javax.swing.JLabel jL_FechaDeCompra;
    private javax.swing.JLabel jL_IDProveedor;
    private javax.swing.JLabel jL_IdCompraTabla;
    private javax.swing.JLabel jL_IdProductoTabla;
    private javax.swing.JLabel jL_NombreDelProducto;
    private javax.swing.JLabel jL_PrecioCosto;
    private javax.swing.JLabel jL_Titulo;
    private javax.swing.JPanel jP_header;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jS_LineaSeparadora;
    private javax.swing.JSeparator jS_LineaSeparadora2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jT_TablaProductos;
    private javax.swing.JTextField jT_cantidad_DetalleCompra;
    private javax.swing.JTextField jT_descripcion_DetalleCompra;
    private javax.swing.JTable jT_idCompra_mostrar;
    private javax.swing.JTable jT_idProdcuto_mostrar;
    private javax.swing.JTextField jT_idProveedor_Compra;
    private javax.swing.JTextField jT_mostrarProveedor_compra;
    private javax.swing.JTextField jT_nombreProducto_DetalleCompra;
    private javax.swing.JTextField jT_precioCosto_DetalleCompra;
    // End of variables declaration//GEN-END:variables

    private void armarCabecera() {
        ArrayList titulos = new ArrayList();
        titulos.add("ID");
        titulos.add("Razon Social");
        titulos.add("Telefono");
        modelo = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                titulos.add("ID");
                titulos.add("Razon Social");
                titulos.add("Telefono");
                return false;
            }

        };
        for (Object titulo : titulos) {
            modelo.addColumn(titulo);
            jT_TablaProductos.setModel(modelo);
        }
    }

    private void cabeceraIdProducto() {
        ArrayList titulos = new ArrayList();
        titulos.add("ID Producto");
        modelo = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                titulos.add("IDProducto");
                return false;
            }

        };
        for (Object titulo : titulos) {
            modelo.addColumn(titulo);
            jT_idProdcuto_mostrar.setModel(modelo);
        }
    }

    private void cabeceraIdCompra() {
        ArrayList titulos = new ArrayList();
        titulos.add("ID Compra");
        modeloCompra = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                titulos.add("ID Compra");
                return false;
            }
        };
        for (Object titulo : titulos) {
            modeloCompra.addColumn(titulo);
        }
        jT_idCompra_mostrar.setModel(modeloCompra);
    }

    public void llenarTabla() {
        List<Proveedor> prove = proveData.obtenerProveedores();
        for (Proveedor proveedor : prove) {
            modelo.addRow(new Object[]{proveedor.getIdProveedor(), proveedor.getRazonSocial()});
        }
    }

    private void llenarIdCompra() {
        modeloCompra.setRowCount(0);
        idCompra = comData.obtenerUltimoIdCompra();
        modeloCompra.addRow(new Object[]{idCompra}); // Agrega solo el ID de la compra a la tabla
    }

    private void llenarIdProducto() {
        modelo.setRowCount(0);
        idProducto = proData.obtenerUltimoIdProducto();
        modelo.addRow(new Object[]{idProducto});
    }

    private void actualizarIdTodo() {
        modelo.setRowCount(0);
        llenarIdCompra();
        llenarIdProducto();
    }
}
