package Vista.menuPrincipal;

import Control.DetalleVentaData;
import Control.ProductoData;
import Modelo.Producto;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Control.VentaData;

/**
 *
 * @author Hugo, APOLO
 */
public class vistaInventario extends javax.swing.JFrame {

    private ProductoData prodData = new ProductoData();
    private DefaultTableModel modelo = new DefaultTableModel();

    int xMouse, yMouse;

    public vistaInventario() {
        initComponents();
        borrarTabla();
        armarCabecera();
        llenarTabla();
    }

    private void borrarTabla() {
        int filas = modelo.getRowCount() - 1;
        for (int i = filas; i >= 0; i--) {
            modelo.removeRow(i);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jB_Eliminar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jP_header = new javax.swing.JPanel();
        HomeBtn = new javax.swing.JPanel();
        HomeBtnTxt = new javax.swing.JLabel();
        BtnExit = new javax.swing.JPanel();
        BtnExitTxt = new javax.swing.JLabel();
        JL_LOGO = new javax.swing.JLabel();
        JL_Titulo = new javax.swing.JLabel();
        jS_tablaProductos = new javax.swing.JScrollPane();
        jT_tablaProductos = new javax.swing.JTable();
        jB_VerificarStock = new javax.swing.JButton();
        jL_idProductoTexto = new javax.swing.JLabel();
        jT_idProducto = new javax.swing.JTextField();
        jB_buscarProducto = new javax.swing.JButton();
        jL_nombreProductoTexto = new javax.swing.JLabel();
        jT_nombresDelProducto = new javax.swing.JTextField();
        jL_descripcion = new javax.swing.JLabel();
        jT_DescripcionProducto = new javax.swing.JTextField();
        jL_stock = new javax.swing.JLabel();
        jT_StockProductos = new javax.swing.JTextField();
        jL_estado = new javax.swing.JLabel();
        jT_Estadoproductos = new javax.swing.JTextField();
        jB_Guarcambios_productos = new javax.swing.JButton();
        jL_tituloProductos = new javax.swing.JLabel();
        jL_precioActual = new javax.swing.JLabel();
        jT_precioactual = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jB_limpiar = new javax.swing.JButton();

        jB_Eliminar.setBackground(new java.awt.Color(255, 51, 51));
        jB_Eliminar.setFont(new java.awt.Font("HP Simplified", 1, 18)); // NOI18N
        jB_Eliminar.setForeground(new java.awt.Color(255, 255, 255));
        jB_Eliminar.setText("ELIMINAR");
        jB_Eliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jB_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_EliminarActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setMaximumSize(new java.awt.Dimension(800, 700));
        setMinimumSize(new java.awt.Dimension(800, 700));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jPanel1.setMaximumSize(new java.awt.Dimension(800, 700));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 700));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 700));

        jP_header.setBackground(new java.awt.Color(51, 51, 51));
        jP_header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jP_headerMouseDragged(evt);
            }
        });
        jP_header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jP_headerMousePressed(evt);
            }
        });

        HomeBtn.setBackground(new java.awt.Color(51, 51, 51));

        HomeBtnTxt.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        HomeBtnTxt.setForeground(new java.awt.Color(255, 255, 255));
        HomeBtnTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HomeBtnTxt.setText("<");
        HomeBtnTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HomeBtnTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeBtnTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HomeBtnTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HomeBtnTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout HomeBtnLayout = new javax.swing.GroupLayout(HomeBtn);
        HomeBtn.setLayout(HomeBtnLayout);
        HomeBtnLayout.setHorizontalGroup(
            HomeBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 92, Short.MAX_VALUE)
            .addGroup(HomeBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(HomeBtnLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(HomeBtnTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        HomeBtnLayout.setVerticalGroup(
            HomeBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(HomeBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(HomeBtnLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(HomeBtnTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        BtnExit.setBackground(new java.awt.Color(51, 51, 51));
        BtnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        BtnExitTxt.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        BtnExitTxt.setForeground(new java.awt.Color(255, 255, 255));
        BtnExitTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtnExitTxt.setText("X");
        BtnExitTxt.setMaximumSize(new java.awt.Dimension(70, 70));
        BtnExitTxt.setMinimumSize(new java.awt.Dimension(70, 70));
        BtnExitTxt.setPreferredSize(new java.awt.Dimension(70, 70));
        BtnExitTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnExitTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnExitTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnExitTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout BtnExitLayout = new javax.swing.GroupLayout(BtnExit);
        BtnExit.setLayout(BtnExitLayout);
        BtnExitLayout.setHorizontalGroup(
            BtnExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BtnExitLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnExitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        BtnExitLayout.setVerticalGroup(
            BtnExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnExitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtnExitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JL_LOGO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagenes/LOGOCHIQUITO.png"))); // NOI18N
        JL_LOGO.setText("jLabel2");

        javax.swing.GroupLayout jP_headerLayout = new javax.swing.GroupLayout(jP_header);
        jP_header.setLayout(jP_headerLayout);
        jP_headerLayout.setHorizontalGroup(
            jP_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_headerLayout.createSequentialGroup()
                .addComponent(HomeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JL_LOGO, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(212, 212, 212)
                .addComponent(BtnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jP_headerLayout.setVerticalGroup(
            jP_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BtnExit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jP_headerLayout.createSequentialGroup()
                .addGroup(jP_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(HomeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JL_LOGO, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        JL_Titulo.setFont(new java.awt.Font("HP Simplified", 1, 24)); // NOI18N
        JL_Titulo.setForeground(new java.awt.Color(204, 0, 204));
        JL_Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JL_Titulo.setText("INVENTARIO");

        jT_tablaProductos.setFont(new java.awt.Font("HP Simplified", 1, 15)); // NOI18N
        jT_tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jT_tablaProductos.setGridColor(new java.awt.Color(51, 51, 51));
        jT_tablaProductos.setPreferredSize(new java.awt.Dimension(800, 275));
        jT_tablaProductos.setSelectionBackground(new java.awt.Color(204, 0, 204));
        jS_tablaProductos.setViewportView(jT_tablaProductos);

        jB_VerificarStock.setFont(new java.awt.Font("HP Simplified", 1, 18)); // NOI18N
        jB_VerificarStock.setText("VERIFICAR STOCK");
        jB_VerificarStock.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jB_VerificarStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_VerificarStockActionPerformed(evt);
            }
        });

        jL_idProductoTexto.setFont(new java.awt.Font("HP Simplified", 1, 15)); // NOI18N
        jL_idProductoTexto.setForeground(new java.awt.Color(255, 255, 255));
        jL_idProductoTexto.setText("ID PRODUCTO");

        jB_buscarProducto.setFont(new java.awt.Font("HP Simplified", 1, 15)); // NOI18N
        jB_buscarProducto.setText("OK");
        jB_buscarProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jB_buscarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_buscarProductoActionPerformed(evt);
            }
        });

        jL_nombreProductoTexto.setFont(new java.awt.Font("HP Simplified", 1, 15)); // NOI18N
        jL_nombreProductoTexto.setForeground(new java.awt.Color(255, 255, 255));
        jL_nombreProductoTexto.setText("NOMBRE DEL PRODUCTO");

        jL_descripcion.setFont(new java.awt.Font("HP Simplified", 1, 15)); // NOI18N
        jL_descripcion.setForeground(new java.awt.Color(255, 255, 255));
        jL_descripcion.setText("DESCRIPCION");

        jL_stock.setFont(new java.awt.Font("HP Simplified", 1, 15)); // NOI18N
        jL_stock.setForeground(new java.awt.Color(255, 255, 255));
        jL_stock.setText("STOCK");

        jL_estado.setFont(new java.awt.Font("HP Simplified", 1, 15)); // NOI18N
        jL_estado.setForeground(new java.awt.Color(255, 255, 255));
        jL_estado.setText("ESTADO");

        jB_Guarcambios_productos.setFont(new java.awt.Font("HP Simplified", 1, 18)); // NOI18N
        jB_Guarcambios_productos.setText("GUARDAR CAMBIOS");
        jB_Guarcambios_productos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jB_Guarcambios_productos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_Guarcambios_productosActionPerformed(evt);
            }
        });

        jL_tituloProductos.setFont(new java.awt.Font("HP Simplified", 1, 24)); // NOI18N
        jL_tituloProductos.setForeground(new java.awt.Color(204, 0, 204));
        jL_tituloProductos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_tituloProductos.setText("PRODUCTO");

        jL_precioActual.setFont(new java.awt.Font("HP Simplified", 1, 15)); // NOI18N
        jL_precioActual.setForeground(new java.awt.Color(255, 255, 255));
        jL_precioActual.setText("PRECIO ACTUAL");

        jB_limpiar.setFont(new java.awt.Font("HP Simplified", 1, 15)); // NOI18N
        jB_limpiar.setText("LIMPIAR");
        jB_limpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jB_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_limpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jP_header, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jL_nombreProductoTexto)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jT_nombresDelProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jL_descripcion)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jT_DescripcionProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(45, 45, 45)
                                                .addComponent(jB_Guarcambios_productos)))
                                        .addGap(49, 49, 49)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jB_limpiar)
                                                .addGap(65, 65, 65)
                                                .addComponent(jB_VerificarStock))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jL_estado)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jT_Estadoproductos, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(519, 519, 519)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jL_precioActual)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jT_precioactual, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jL_stock)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jT_StockProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(jS_tablaProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 793, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JL_Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 801, Short.MAX_VALUE)
                                    .addComponent(jSeparator1))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(27, 27, 27)
                                    .addComponent(jL_tituloProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 745, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(289, 289, 289)
                                    .addComponent(jL_idProductoTexto)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jT_idProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jB_buscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 801, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jP_header, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(JL_Titulo)
                .addGap(18, 18, 18)
                .addComponent(jS_tablaProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jL_tituloProductos)
                .addGap(2, 2, 2)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jB_buscarProducto)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jL_idProductoTexto)
                        .addComponent(jT_idProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_nombreProductoTexto)
                    .addComponent(jT_nombresDelProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL_precioActual)
                    .addComponent(jT_precioactual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_descripcion)
                    .addComponent(jT_DescripcionProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL_stock)
                    .addComponent(jT_StockProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL_estado)
                    .addComponent(jT_Estadoproductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_Guarcambios_productos)
                    .addComponent(jB_VerificarStock)
                    .addComponent(jB_limpiar))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Boton stock
    private void jB_VerificarStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_VerificarStockActionPerformed
        String nombreProducto = JOptionPane.showInputDialog(this, "Ingrese el nombre del producto:");

        if (nombreProducto != null && !nombreProducto.isEmpty()) {
            ProductoData productoData = new ProductoData();
            List<Producto> productosEncontrados = productoData.buscarProductoPorNombre(nombreProducto);

            if (productosEncontrados.isEmpty()) {
                JOptionPane.showMessageDialog(this, "No se encontraron productos con ese nombre.");
            } else {
                StringBuilder mensaje = new StringBuilder();
                for (Producto producto : productosEncontrados) {
                    int idProducto = producto.getIdProducto();
                    int cantidadDeseada = obtenerCantidadDeseada();
                    boolean stockSuficiente = productoData.verificarStockSuficiente(idProducto, cantidadDeseada);
                    String estadoStock = stockSuficiente ? "Hay stock para la cantidad deseada" : "No hay stock para la cantidad deseada";

                    mensaje.append("Nombre: ").append(producto.getNombreProducto()).append("\n");
                    mensaje.append("Descripción: ").append(producto.getDescripcion()).append("\n");
                    mensaje.append("Precio: ").append(producto.getPrecioActual()).append("\n");
                    mensaje.append("Stock Disponible: ").append(producto.getStock()).append("\n");
                    mensaje.append("-----------------------------------------").append("\n");
                    mensaje.append("").append(estadoStock).append("\n\n");
                }
                JOptionPane.showMessageDialog(this, mensaje.toString());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Debe ingresar un nombre de producto.");
        }

    }//GEN-LAST:event_jB_VerificarStockActionPerformed

    private void jB_buscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_buscarProductoActionPerformed
        // TODO add your handling code here:
        try {
            int id = Integer.parseInt(jT_idProducto.getText());
            Producto productoEncontrado = prodData.buscarProductoPorId2(id);
            if (productoEncontrado != null) {
                String nomb = productoEncontrado.getNombreProducto();
                String descrip = productoEncontrado.getDescripcion();
                double precio = productoEncontrado.getPrecioActual();
                int stock = productoEncontrado.getStock();
                boolean estado = productoEncontrado.isEstado();

                jT_nombresDelProducto.setText(nomb);
                jT_DescripcionProducto.setText(descrip);
                jT_StockProductos.setText(String.valueOf(stock));
                jT_precioactual.setText(String.valueOf(precio));
                jT_Estadoproductos.setText(String.valueOf(estado));

            } else {
                JOptionPane.showMessageDialog(this, "Producto  no encontrado.");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al buscar." + ex.getMessage());
        }
    }//GEN-LAST:event_jB_buscarProductoActionPerformed

    private void jB_Guarcambios_productosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_Guarcambios_productosActionPerformed
        // TODO add your handling code here:
        try {
            int id = Integer.parseInt(jT_idProducto.getText());
            String nom = jT_nombresDelProducto.getText();
            String descrop = jT_DescripcionProducto.getText();
            double precio = Double.parseDouble(jT_precioactual.getText());
            int stock = Integer.parseInt(jT_StockProductos.getText());
            boolean estado = Boolean.parseBoolean(jT_Estadoproductos.getText());

            Producto pro = new Producto(id, nom, descrop, precio, stock, estado);
            prodData.actualizarProducto2(pro);
            borrarTabla();
            llenarTabla();
            JOptionPane.showMessageDialog(this, "Modificacion Exitosa.");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al modificar." + ex.getMessage());
        }
    }//GEN-LAST:event_jB_Guarcambios_productosActionPerformed

    // Boton eliminar producto
    private void jB_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_EliminarActionPerformed
        try {
            // Obtener el ID del producto a eliminar
            int idProducto = Integer.parseInt(jT_idProducto.getText());

            // Crear una instancia de DetalleVentaData
            DetalleVentaData detalleVentaData = new DetalleVentaData();

            // Verificar si hay detalles de venta asociados al producto
            boolean tieneDetallesVenta = detalleVentaData.verificarProductoEnDetallesVenta(idProducto);

            if (tieneDetallesVenta) {
                // Mostrar un mensaje de error indicando que el producto no se puede eliminar debido a las ventas asociadas
                JOptionPane.showMessageDialog(this, "No se puede eliminar el producto porque tiene ventas asociadas.");
            } else {
                // Si no hay detalles de venta asociados, eliminar el producto
                prodData.eliminarProducto(idProducto);
                JOptionPane.showMessageDialog(this, "Producto eliminado exitosamente.");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al eliminar el producto de la base de datos: " + ex.getMessage());
        }

    }//GEN-LAST:event_jB_EliminarActionPerformed

    // Botones Header
    private void HomeBtnTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeBtnTxtMouseClicked
        dispose();
        principalMenu menu = new principalMenu();
        menu.setVisible(true);
    }//GEN-LAST:event_HomeBtnTxtMouseClicked

    private void HomeBtnTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeBtnTxtMouseEntered
        HomeBtn.setBackground(Color.MAGENTA);
    }//GEN-LAST:event_HomeBtnTxtMouseEntered

    private void HomeBtnTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeBtnTxtMouseExited
        HomeBtn.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_HomeBtnTxtMouseExited

    private void BtnExitTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnExitTxtMouseClicked
        int option = JOptionPane.showConfirmDialog(this, "¿Estás seguro de que queres cerrar el programa?", "Confirmar cierre", JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_BtnExitTxtMouseClicked

    private void BtnExitTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnExitTxtMouseEntered
        BtnExit.setBackground(Color.RED);
    }//GEN-LAST:event_BtnExitTxtMouseEntered

    private void BtnExitTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnExitTxtMouseExited
        BtnExit.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_BtnExitTxtMouseExited

    private void jP_headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_headerMouseDragged
        //Esto hace que se pueda draggear el programa
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jP_headerMouseDragged

    private void jP_headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jP_headerMousePressed

    //Boton limpiar
    private void jB_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_limpiarActionPerformed
        // Limpiar los campos de búsqueda
        jT_idProducto.setText("");
        jT_nombresDelProducto.setText("");
        jT_DescripcionProducto.setText("");
        jT_StockProductos.setText("");
        jT_precioactual.setText("");
        jT_Estadoproductos.setText("");
    }//GEN-LAST:event_jB_limpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaInventario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BtnExit;
    private javax.swing.JLabel BtnExitTxt;
    private javax.swing.JPanel HomeBtn;
    private javax.swing.JLabel HomeBtnTxt;
    private javax.swing.JLabel JL_LOGO;
    private javax.swing.JLabel JL_Titulo;
    private javax.swing.JButton jB_Eliminar;
    private javax.swing.JButton jB_Guarcambios_productos;
    private javax.swing.JButton jB_VerificarStock;
    private javax.swing.JButton jB_buscarProducto;
    private javax.swing.JButton jB_limpiar;
    private javax.swing.JLabel jL_descripcion;
    private javax.swing.JLabel jL_estado;
    private javax.swing.JLabel jL_idProductoTexto;
    private javax.swing.JLabel jL_nombreProductoTexto;
    private javax.swing.JLabel jL_precioActual;
    private javax.swing.JLabel jL_stock;
    private javax.swing.JLabel jL_tituloProductos;
    private javax.swing.JPanel jP_header;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jS_tablaProductos;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jT_DescripcionProducto;
    private javax.swing.JTextField jT_Estadoproductos;
    private javax.swing.JTextField jT_StockProductos;
    private javax.swing.JTextField jT_idProducto;
    private javax.swing.JTextField jT_nombresDelProducto;
    private javax.swing.JTextField jT_precioactual;
    private javax.swing.JTable jT_tablaProductos;
    // End of variables declaration//GEN-END:variables

    //Tabla Inventario
    private void armarCabecera() {
        ArrayList titulos = new ArrayList();
        titulos.add("ID ");
        titulos.add("Nombre ");
        titulos.add("Descripcion");
        titulos.add("Precio");
        titulos.add("Stock");
        titulos.add("Estado");
        modelo = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                titulos.add("ID ");
                titulos.add("Nombre ");
                titulos.add("Descripcion");
                titulos.add("Precio");
                titulos.add("Stock");
                titulos.add("Estado");
                return false;
            }

        };
        for (Object titulo : titulos) {
            modelo.addColumn(titulo);
            jT_tablaProductos.setModel(modelo);
        }
    }

    private void llenarTabla() {
        borrarTabla();
        List<Producto> productos = prodData.obtenerProductosTodos();
        for (Producto producto : productos) {
            String estado = producto.isEstado() ? "Activo" : "No Activo";
            modelo.addRow(new Object[]{
                producto.getIdProducto(),
                producto.getNombreProducto(),
                producto.getDescripcion(),
                producto.getPrecioActual(),
                producto.getStock(),
                estado
            });
        }
    }

    private int obtenerCantidadDeseada() {
        int cantidadDeseada = 0;
        String cantidadText = JOptionPane.showInputDialog(this, "Ingresa la cantidad deseada:", "VERIFICAR STOCK", JOptionPane.PLAIN_MESSAGE);
        try {
            cantidadDeseada = Integer.parseInt(cantidadText);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingresa una cantidad válida.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        return cantidadDeseada;
    }

}
