package Vista.menuPrincipal;

import Control.ProveedorData;
import Modelo.Proveedor;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hugo, APOLO
 */
public class vistaProveedor extends javax.swing.JFrame {

    private ProveedorData proData = new ProveedorData();
    private DefaultTableModel modelo = new DefaultTableModel();

    int xMouse, yMouse;

    public vistaProveedor() {
        initComponents();
        armarCabecera();
        borrarTabla();
        llenarTabla();

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jP_header = new javax.swing.JPanel();
        HomeBtn = new javax.swing.JPanel();
        HomeBtnTxt = new javax.swing.JLabel();
        BtnExit = new javax.swing.JPanel();
        BtnExitTxt = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jL_Titulo = new javax.swing.JLabel();
        jS_LineaSeparadora = new javax.swing.JSeparator();
        jL_iDProveedor = new javax.swing.JLabel();
        jT_iDProveedor = new javax.swing.JTextField();
        jB_buscar = new javax.swing.JButton();
        jS_LineaSeparadora2 = new javax.swing.JSeparator();
        jL_razonSocialProveedor = new javax.swing.JLabel();
        jT_razonSocialProveedor = new javax.swing.JTextField();
        jL_domicilioProveedor = new javax.swing.JLabel();
        jT_domicilioProveedor = new javax.swing.JTextField();
        jL_telefonoProveedor = new javax.swing.JLabel();
        jT_telefonoProveedor = new javax.swing.JTextField();
        jB_agregarProveedor = new javax.swing.JButton();
        jB_editarProveedor = new javax.swing.JButton();
        jB_limpiar = new javax.swing.JButton();
        jB_eliminarProveedor = new javax.swing.JButton();
        jL_TituloNuestrosProveedores = new javax.swing.JLabel();
        jS_tablaProveedores = new javax.swing.JScrollPane();
        jT_tablaProveedor = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(800, 700));
        setMinimumSize(new java.awt.Dimension(800, 700));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(800, 700));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 700));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 700));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jP_header.setBackground(new java.awt.Color(51, 51, 51));
        jP_header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jP_headerMouseDragged(evt);
            }
        });
        jP_header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jP_headerMousePressed(evt);
            }
        });

        HomeBtn.setBackground(new java.awt.Color(51, 51, 51));

        HomeBtnTxt.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        HomeBtnTxt.setForeground(new java.awt.Color(255, 255, 255));
        HomeBtnTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HomeBtnTxt.setText("<");
        HomeBtnTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HomeBtnTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeBtnTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HomeBtnTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HomeBtnTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout HomeBtnLayout = new javax.swing.GroupLayout(HomeBtn);
        HomeBtn.setLayout(HomeBtnLayout);
        HomeBtnLayout.setHorizontalGroup(
            HomeBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 92, Short.MAX_VALUE)
            .addGroup(HomeBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(HomeBtnLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(HomeBtnTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        HomeBtnLayout.setVerticalGroup(
            HomeBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(HomeBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(HomeBtnLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(HomeBtnTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        BtnExit.setBackground(new java.awt.Color(51, 51, 51));
        BtnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        BtnExitTxt.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        BtnExitTxt.setForeground(new java.awt.Color(255, 255, 255));
        BtnExitTxt.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnExitTxt.setText("      x");
        BtnExitTxt.setMaximumSize(new java.awt.Dimension(70, 70));
        BtnExitTxt.setMinimumSize(new java.awt.Dimension(70, 70));
        BtnExitTxt.setPreferredSize(new java.awt.Dimension(70, 70));
        BtnExitTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnExitTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnExitTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnExitTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout BtnExitLayout = new javax.swing.GroupLayout(BtnExit);
        BtnExit.setLayout(BtnExitLayout);
        BtnExitLayout.setHorizontalGroup(
            BtnExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BtnExitLayout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(BtnExitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        BtnExitLayout.setVerticalGroup(
            BtnExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnExitLayout.createSequentialGroup()
                .addComponent(BtnExitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagenes/LOGOCHIQUITO.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout jP_headerLayout = new javax.swing.GroupLayout(jP_header);
        jP_header.setLayout(jP_headerLayout);
        jP_headerLayout.setHorizontalGroup(
            jP_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_headerLayout.createSequentialGroup()
                .addComponent(HomeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(212, 212, 212)
                .addComponent(BtnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jP_headerLayout.setVerticalGroup(
            jP_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BtnExit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jP_headerLayout.createSequentialGroup()
                .addGroup(jP_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(HomeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jL_Titulo.setBackground(new java.awt.Color(51, 51, 51));
        jL_Titulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jL_Titulo.setForeground(new java.awt.Color(204, 0, 204));
        jL_Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_Titulo.setText(" PROVEEDORES");

        jL_iDProveedor.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jL_iDProveedor.setForeground(new java.awt.Color(255, 255, 255));
        jL_iDProveedor.setText("ID Proveedor");

        jT_iDProveedor.setFont(new java.awt.Font("HP Simplified", 1, 15)); // NOI18N
        jT_iDProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_iDProveedorActionPerformed(evt);
            }
        });

        jB_buscar.setBackground(new java.awt.Color(255, 255, 255));
        jB_buscar.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jB_buscar.setForeground(new java.awt.Color(0, 0, 0));
        jB_buscar.setText("Buscar");
        jB_buscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jB_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_buscarActionPerformed(evt);
            }
        });

        jL_razonSocialProveedor.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jL_razonSocialProveedor.setForeground(new java.awt.Color(255, 255, 255));
        jL_razonSocialProveedor.setText("Razón Social");

        jT_razonSocialProveedor.setFont(new java.awt.Font("HP Simplified", 1, 15)); // NOI18N

        jL_domicilioProveedor.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jL_domicilioProveedor.setForeground(new java.awt.Color(255, 255, 255));
        jL_domicilioProveedor.setText("Domicilio");

        jT_domicilioProveedor.setFont(new java.awt.Font("HP Simplified", 1, 15)); // NOI18N

        jL_telefonoProveedor.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jL_telefonoProveedor.setForeground(new java.awt.Color(255, 255, 255));
        jL_telefonoProveedor.setText("Teléfono");

        jT_telefonoProveedor.setFont(new java.awt.Font("HP Simplified", 1, 15)); // NOI18N

        jB_agregarProveedor.setBackground(new java.awt.Color(255, 255, 255));
        jB_agregarProveedor.setFont(new java.awt.Font("HP Simplified", 1, 18)); // NOI18N
        jB_agregarProveedor.setForeground(new java.awt.Color(0, 0, 0));
        jB_agregarProveedor.setText("Agregar ");
        jB_agregarProveedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jB_agregarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_agregarProveedorActionPerformed(evt);
            }
        });

        jB_editarProveedor.setBackground(new java.awt.Color(255, 255, 255));
        jB_editarProveedor.setFont(new java.awt.Font("HP Simplified", 1, 18)); // NOI18N
        jB_editarProveedor.setForeground(new java.awt.Color(0, 0, 0));
        jB_editarProveedor.setText("Editar");
        jB_editarProveedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jB_editarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_editarProveedorActionPerformed(evt);
            }
        });

        jB_limpiar.setBackground(new java.awt.Color(255, 255, 255));
        jB_limpiar.setFont(new java.awt.Font("HP Simplified", 1, 18)); // NOI18N
        jB_limpiar.setForeground(new java.awt.Color(0, 0, 0));
        jB_limpiar.setText("Limpiar");
        jB_limpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jB_limpiar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jB_limpiar.setMaximumSize(new java.awt.Dimension(90, 30));
        jB_limpiar.setMinimumSize(new java.awt.Dimension(90, 30));
        jB_limpiar.setPreferredSize(new java.awt.Dimension(90, 30));
        jB_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_limpiarActionPerformed(evt);
            }
        });

        jB_eliminarProveedor.setBackground(new java.awt.Color(255, 0, 51));
        jB_eliminarProveedor.setFont(new java.awt.Font("HP Simplified", 1, 18)); // NOI18N
        jB_eliminarProveedor.setForeground(new java.awt.Color(255, 255, 255));
        jB_eliminarProveedor.setText("Eliminar");
        jB_eliminarProveedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jB_eliminarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_eliminarProveedorActionPerformed(evt);
            }
        });

        jL_TituloNuestrosProveedores.setFont(new java.awt.Font("HP Simplified", 1, 18)); // NOI18N
        jL_TituloNuestrosProveedores.setForeground(new java.awt.Color(204, 0, 204));
        jL_TituloNuestrosProveedores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_TituloNuestrosProveedores.setText("NUESTROS PROVEEDORES");
        jL_TituloNuestrosProveedores.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jS_tablaProveedores.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(102, 102, 102)));

        jT_tablaProveedor.setFont(new java.awt.Font("HP Simplified", 0, 15)); // NOI18N
        jT_tablaProveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Titulo 1", "Titulo 2", "Titulo 3", "Titulo 4"
            }
        ));
        jT_tablaProveedor.setSelectionBackground(new java.awt.Color(204, 0, 204));
        jS_tablaProveedores.setViewportView(jT_tablaProveedor);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jL_razonSocialProveedor)
                                    .addComponent(jL_iDProveedor))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addComponent(jT_iDProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jB_buscar))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(jT_razonSocialProveedor))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jL_domicilioProveedor)
                                    .addComponent(jL_telefonoProveedor)
                                    .addComponent(jB_agregarProveedor))
                                .addGap(40, 40, 40)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jT_domicilioProveedor, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jT_telefonoProveedor, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(jB_editarProveedor)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jB_limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jB_eliminarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(223, 223, 223))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jS_tablaProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(176, 176, 176))))
            .addComponent(jL_TituloNuestrosProveedores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(812, 812, 812)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jL_Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jS_LineaSeparadora, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jS_LineaSeparadora2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jP_header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jP_header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jL_Titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jS_LineaSeparadora, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_iDProveedor)
                    .addComponent(jT_iDProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_buscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jS_LineaSeparadora2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_razonSocialProveedor)
                    .addComponent(jT_razonSocialProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jL_domicilioProveedor)
                    .addComponent(jT_domicilioProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jL_telefonoProveedor)
                    .addComponent(jT_telefonoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_editarProveedor)
                    .addComponent(jB_agregarProveedor)
                    .addComponent(jB_limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jB_eliminarProveedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jL_TituloNuestrosProveedores)
                .addGap(35, 35, 35)
                .addComponent(jS_tablaProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void armarCabecera() {
        ArrayList titulos = new ArrayList();
        titulos.add("ID");
        titulos.add("Razon Social");
        titulos.add("Domicilio");
        titulos.add("Telefono");
        modelo = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                titulos.add("ID");
                titulos.add("Razon Social");
                titulos.add("Domicilio");
                titulos.add("Telefono");
                return false;
            }

        };
        for (Object titulo : titulos) {
            modelo.addColumn(titulo);
            jT_tablaProveedor.setModel(modelo);
        }

    }

    public void llenarTabla() {
        List<Proveedor> proveedores = proData.obtenerProveedores();
        for (Proveedor proveedor : proveedores) {
            modelo.addRow(new Object[]{proveedor.getIdProveedor(), proveedor.getRazonSocial(), proveedor.getDomicilio(), proveedor.getTelefono()});
        }
    }

    private void borrarTabla() {
        int filas = modelo.getRowCount() - 1;
        for (int i = filas; i >= 0; i--) {
            modelo.removeRow(i);
        }
    }

    //Limpia los campos de texto
    private void limpiar() {
        jT_domicilioProveedor.setText("");
        jT_iDProveedor.setText("");
        jT_razonSocialProveedor.setText("");
        jT_telefonoProveedor.setText("");
    }

    private void jB_agregarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_agregarProveedorActionPerformed
        try {
            String razon = jT_razonSocialProveedor.getText();
            String dom = jT_domicilioProveedor.getText();
            String tel = jT_telefonoProveedor.getText();

            Proveedor pro = new Proveedor(razon, dom, tel);
            proData.agregarProveedor(pro);

            // Mostrar una alerta con el ID asignado al proveedor
            JOptionPane.showMessageDialog(this, "Proveedor agregado correctamente a la base de datos");

            // Actualizar la tabla de proveedores
            borrarTabla();
            llenarTabla();
            limpiar();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al agregar proveedor." + ex.getMessage());
        }
    }//GEN-LAST:event_jB_agregarProveedorActionPerformed

    private void jT_iDProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_iDProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_iDProveedorActionPerformed

    private void jB_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_buscarActionPerformed
        // TODO add your handling code here:
        try {
            int id = Integer.parseInt(jT_iDProveedor.getText());
            Proveedor proEncontrado = proData.buscarProveedor(id);
            if (proEncontrado != null) {
                String razon = proEncontrado.getRazonSocial();
                String dom = proEncontrado.getDomicilio();
                String tel = proEncontrado.getTelefono();
                jT_razonSocialProveedor.setText(razon);
                jT_domicilioProveedor.setText(dom);
                jT_telefonoProveedor.setText(tel);
            } else {
                JOptionPane.showMessageDialog(this, "Proveedor no encontrado.");
                //Agregar limpiar.
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al buscar." + ex.getMessage());
        }
    }//GEN-LAST:event_jB_buscarActionPerformed

    private void jB_eliminarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_eliminarProveedorActionPerformed
        try {
            int id = Integer.parseInt(jT_iDProveedor.getText());

            // Obtener la razón social del proveedor
            Proveedor proveedor = proData.buscarProveedor(id);
            String razonSocial = proveedor.getRazonSocial();

            // Mostrar una alerta de confirmación con la razón social
            int option = JOptionPane.showConfirmDialog(this, "¿Estás seguro de que quieres eliminar al proveedor: " + razonSocial + "?", "Eliminar Proveedor", JOptionPane.YES_NO_OPTION);
            if (option == JOptionPane.YES_OPTION) {
                proData.eliminarProveedor(id);
                JOptionPane.showMessageDialog(this, "Proveedor eliminado.");

                // Actualizar la tabla de proveedores
                borrarTabla();
                llenarTabla();
                limpiar();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al eliminar proveedor." + ex.getMessage());
        }
    }//GEN-LAST:event_jB_eliminarProveedorActionPerformed

    private void jB_editarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_editarProveedorActionPerformed
        // TODO add your handling code here:
        try {
            int id = Integer.parseInt(jT_iDProveedor.getText());
            String razon = jT_razonSocialProveedor.getText();
            String dom = jT_domicilioProveedor.getText();
            String tel = jT_telefonoProveedor.getText();
            Proveedor pro = new Proveedor(id, razon, dom, tel);
            proData.modificarProveedor(pro);
            JOptionPane.showMessageDialog(this, "Proveedor Modificado.");
            borrarTabla();
            llenarTabla();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error el Modificar proveedor." + ex.getMessage());
        }
    }//GEN-LAST:event_jB_editarProveedorActionPerformed

    private void HomeBtnTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeBtnTxtMouseClicked
        dispose();
        principalMenu log = new principalMenu();
        log.setVisible(true);
    }//GEN-LAST:event_HomeBtnTxtMouseClicked

    private void HomeBtnTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeBtnTxtMouseEntered
        HomeBtn.setBackground(Color.MAGENTA);
    }//GEN-LAST:event_HomeBtnTxtMouseEntered

    private void HomeBtnTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeBtnTxtMouseExited
        HomeBtn.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_HomeBtnTxtMouseExited

    private void BtnExitTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnExitTxtMouseClicked
        int option = JOptionPane.showConfirmDialog(this, "¿Estás seguro de que queres cerrar el programa?", "Confirmar cierre", JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_BtnExitTxtMouseClicked

    private void BtnExitTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnExitTxtMouseEntered
        BtnExit.setBackground(Color.RED);
    }//GEN-LAST:event_BtnExitTxtMouseEntered

    private void BtnExitTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnExitTxtMouseExited
        BtnExit.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_BtnExitTxtMouseExited

    private void jP_headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_headerMouseDragged
        //Esto hace que se pueda draggear el programa
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jP_headerMouseDragged

    private void jP_headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jP_headerMousePressed

    private void jB_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_limpiarActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_jB_limpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaProveedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BtnExit;
    private javax.swing.JLabel BtnExitTxt;
    private javax.swing.JPanel HomeBtn;
    private javax.swing.JLabel HomeBtnTxt;
    private javax.swing.JButton jB_agregarProveedor;
    private javax.swing.JButton jB_buscar;
    private javax.swing.JButton jB_editarProveedor;
    private javax.swing.JButton jB_eliminarProveedor;
    private javax.swing.JButton jB_limpiar;
    private javax.swing.JLabel jL_Titulo;
    private javax.swing.JLabel jL_TituloNuestrosProveedores;
    private javax.swing.JLabel jL_domicilioProveedor;
    private javax.swing.JLabel jL_iDProveedor;
    private javax.swing.JLabel jL_razonSocialProveedor;
    private javax.swing.JLabel jL_telefonoProveedor;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jP_header;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jS_LineaSeparadora;
    private javax.swing.JSeparator jS_LineaSeparadora2;
    private javax.swing.JScrollPane jS_tablaProveedores;
    private javax.swing.JTextField jT_domicilioProveedor;
    private javax.swing.JTextField jT_iDProveedor;
    private javax.swing.JTextField jT_razonSocialProveedor;
    private javax.swing.JTable jT_tablaProveedor;
    private javax.swing.JTextField jT_telefonoProveedor;
    // End of variables declaration//GEN-END:variables
}
