/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista.menuPrincipal;

import Control.CompraData;
import Control.DetalleCompraData;
import Control.ProductoData;
import Control.ProveedorData;
import Modelo.Compra;
import Modelo.DetalleCompra;
import Modelo.Producto;
import Modelo.Proveedor;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hugo
 */
public class vistaCompra extends javax.swing.JFrame {
    private DefaultTableModel modelo = new DefaultTableModel();
    private ProveedorData proveData = new ProveedorData();
    private CompraData comData = new CompraData();
    private ProductoData proData = new ProductoData();
    private DetalleCompraData detalleData = new DetalleCompraData();
    private int idCompra; // Variable para almacenar el ID de la compra
    private int idProducto; // Variable para almacenar el ID del producto
    /**
     * Creates new form vistaCompra
     */
    public vistaCompra() {
        initComponents();
        armarCabecera();
        llenarTabla();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jT_idProveedor_Compra = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jT_Mostrarfecha_Compra = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jT_TablaProductos = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jB_compra = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jB_buscarProveedor_compra = new javax.swing.JButton();
        jT_mostrarProveedor_compra = new javax.swing.JTextField();
        jB_historialCompra = new javax.swing.JButton();
        jT_cantidad_DetalleCompra = new javax.swing.JTextField();
        jC_FechaCompra = new com.toedter.calendar.JCalendar();
        jLabel5 = new javax.swing.JLabel();
        jT_nombreProducto_DetalleCompra = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jT_precioCosto_DetalleCompra = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jT_descripcion_DetalleCompra = new javax.swing.JTextField();
        jB_guardarDetalle = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Compra");

        jLabel2.setText("id Proveedor");

        jLabel3.setText("Fecha");

        jT_TablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jT_TablaProductos);

        jLabel4.setText("Cantidad");

        jB_compra.setText("Comprar");
        jB_compra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_compraActionPerformed(evt);
            }
        });

        jLabel7.setText("Detalle de Compra");

        jB_buscarProveedor_compra.setText("Buscar");
        jB_buscarProveedor_compra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_buscarProveedor_compraActionPerformed(evt);
            }
        });

        jB_historialCompra.setText("Historial Compra");
        jB_historialCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_historialCompraActionPerformed(evt);
            }
        });

        jC_FechaCompra.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jC_FechaCompraPropertyChange(evt);
            }
        });

        jLabel5.setText("Nombre del Producto");

        jLabel8.setText("Precio Costo");

        jLabel6.setText("Descripcion");

        jB_guardarDetalle.setText("Guardar Detalle ");
        jB_guardarDetalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_guardarDetalleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(270, 270, 270))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jT_mostrarProveedor_compra, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                            .addComponent(jT_idProveedor_Compra))
                        .addGap(58, 58, 58)
                        .addComponent(jB_buscarProveedor_compra)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jB_compra)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4)
                                .addComponent(jLabel8)
                                .addComponent(jLabel6)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jT_nombreProducto_DetalleCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jB_historialCompra)
                                .addGap(18, 18, 18)
                                .addComponent(jB_guardarDetalle))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jT_descripcion_DetalleCompra, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                                .addComponent(jT_precioCosto_DetalleCompra, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jT_cantidad_DetalleCompra, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel3)
                                .addGap(46, 46, 46))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jT_Mostrarfecha_Compra, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addComponent(jC_FechaCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jT_idProveedor_Compra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jB_buscarProveedor_compra))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jT_mostrarProveedor_compra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jT_Mostrarfecha_Compra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jC_FechaCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jT_nombreProducto_DetalleCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jT_cantidad_DetalleCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jT_precioCosto_DetalleCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jT_descripcion_DetalleCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_compra)
                    .addComponent(jB_historialCompra)
                    .addComponent(jB_guardarDetalle))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jB_buscarProveedor_compraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_buscarProveedor_compraActionPerformed
        // TODO add your handling code here:
        try{
          int id = Integer.parseInt(jT_idProveedor_Compra.getText());
          Proveedor proEncontrado = proveData.buscarProveedor(id);
          if(proEncontrado != null){
              String razon = proEncontrado.getRazonSocial();
              //String dom = proEncontrado.getDomicilio();
              //String tel = proEncontrado.getTelefono();
              jT_mostrarProveedor_compra.setText(razon);
              //jT_domicilioProveedor.setText(dom);
              //jT_telefonoProveedor.setText(tel);
          }else{
              JOptionPane.showMessageDialog(this, "Proveedor no encontrado.");
              //Agregar limpiar.
          }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Error al buscar."+ex.getMessage());
        }
    }//GEN-LAST:event_jB_buscarProveedor_compraActionPerformed

    private void jC_FechaCompraPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jC_FechaCompraPropertyChange
        // TODO add your handling code here:
        if(evt.getOldValue()!= null){
             SimpleDateFormat ff = new SimpleDateFormat("dd/MM/yyyy");
             jT_Mostrarfecha_Compra.setText(ff.format(jC_FechaCompra.getCalendar().getTime()));
             
         }
    }//GEN-LAST:event_jC_FechaCompraPropertyChange

    private void jB_compraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_compraActionPerformed
        // TODO add your handling code here:
        try {
        //Registrando Compra..
        int idProveedor = Integer.parseInt(jT_idProveedor_Compra.getText());
        SimpleDateFormat ff = new SimpleDateFormat("dd/MM/yyyy");
        ff.format(jC_FechaCompra.getCalendar().getTime());
        LocalDate fechaNacimiento = jC_FechaCompra.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        Compra comp = new Compra(idProveedor, fechaNacimiento);
        comData.registrarCompra(comp);

        try {
            //COMPRANDO PRODUCTO..
            String nom = jT_nombreProducto_DetalleCompra.getText();
            int cantidad = Integer.parseInt(jT_cantidad_DetalleCompra.getText());
            Double precio = Double.parseDouble(jT_precioCosto_DetalleCompra.getText());
            String descrip = jT_descripcion_DetalleCompra.getText();
            Producto prod = new Producto(nom, descrip, precio, cantidad, true);
            proData.agregarProducto(prod);
        } catch(Exception e) {
            JOptionPane.showMessageDialog(this, "Error al comprar el producto." + e.getMessage());
        }
    } catch(Exception ex) {
        JOptionPane.showMessageDialog(this, "Error al registar compra." + ex.getMessage());
    }
    }//GEN-LAST:event_jB_compraActionPerformed

    private void jB_historialCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_historialCompraActionPerformed
        // TODO add your handling code here:
        dispose();
        vistaDetalleCompra detalle = new vistaDetalleCompra();
        detalle.setVisible(true);
    }//GEN-LAST:event_jB_historialCompraActionPerformed

    private void jB_guardarDetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_guardarDetalleActionPerformed
        // TODO add your handling code here:
        try {
        // Obtener los datos necesarios para el detalle de compra
        int cantidad = Integer.parseInt(jT_cantidad_DetalleCompra.getText());
        Double precio = Double.parseDouble(jT_precioCosto_DetalleCompra.getText());

        // Crear el objeto DetalleCompra y guardar en la base de datos
        DetalleCompra detalle = new DetalleCompra(cantidad, precio, idCompra, idProducto);
        detalleData.agregarDetalleCompra(detalle);

        // Restablecer los campos del formulario o realizar alguna acción adicional si es necesario

    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Error al guardar el detalle de compra: " + ex.getMessage());
    }
    }//GEN-LAST:event_jB_guardarDetalleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaCompra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_buscarProveedor_compra;
    private javax.swing.JButton jB_compra;
    private javax.swing.JButton jB_guardarDetalle;
    private javax.swing.JButton jB_historialCompra;
    private com.toedter.calendar.JCalendar jC_FechaCompra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jT_Mostrarfecha_Compra;
    private javax.swing.JTable jT_TablaProductos;
    private javax.swing.JTextField jT_cantidad_DetalleCompra;
    private javax.swing.JTextField jT_descripcion_DetalleCompra;
    private javax.swing.JTextField jT_idProveedor_Compra;
    private javax.swing.JTextField jT_mostrarProveedor_compra;
    private javax.swing.JTextField jT_nombreProducto_DetalleCompra;
    private javax.swing.JTextField jT_precioCosto_DetalleCompra;
    // End of variables declaration//GEN-END:variables

    private void armarCabecera() {
       ArrayList titulos = new ArrayList();
       titulos.add("ID");
       titulos.add("Razon Social");
       modelo = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
            titulos.add("ID");
            titulos.add("Razon Social");
            return false;
        }
            
        };
        for (Object titulo : titulos) {
            modelo.addColumn(titulo);
                jT_TablaProductos.setModel(modelo);
        }
    }

    public void llenarTabla() {
        List<Proveedor> prove = proveData.obtenerProveedores();
        for (Proveedor proveedor : prove) {
            modelo.addRow(new Object[]{proveedor.getIdProveedor(),proveedor.getRazonSocial()});
        }
        }
//    List<Producto> productos = proData.obtenerProductos();
//   // borrarTabla(); // Eliminar los datos existentes en la tabla antes de mostrar los nuevos datos
//    for (Producto producto : productos) {
//        modelo.addRow(new Object[]{producto.getIdProducto(), producto.getNombreProducto(), producto.getPrecioActual(), producto.getStock()});
//    }
}

